/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OtroFrame.java
 *
 * Created on 21-abr-2009, 22:36:42
 */
package caafe.cliente;

import caafes.def.Clientes;
import clientes.servicio.ServicioCliente;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.JOptionPane;
import otro.MiFrame;
import otro.Pass;

/**
 *
 * @author Edgar
 */
public class Cliente extends MiFrame {

    private Clientes nuevo = null;
    private Pass frmPass = null;
    private Boolean bEstado = null;
    private int iEstatus;
    public final static int NUEVO = 100;
    public final static int CONSULTAR = 101;
    public final static int EDITAR = 102;

    /** Creates new form OtroFrame */
    public Cliente() {
        initComponents();
    }

    public void actualizaForm(int iEstatus, BigDecimal iDCliente) {
        this.iEstatus = iEstatus;

        if (iEstatus == CONSULTAR) {
            jtxNombre.setEnabled(false);
            jtxApellido.setEnabled(false);
            jtxRFC.setEnabled(false);
            jtxTelefono.setEnabled(false);
            jtxCalleNumero.setEnabled(false);
            jtxCiudad.setEnabled(false);
            jtxCodigoPostal.setEnabled(false);
            jtxColonia.setEnabled(false);
            jtxDelegacion.setEnabled(false);
            ServicioCliente srvCliente = new ServicioCliente();

            nuevo = srvCliente.obtieneCliente(iDCliente, null);

            jtxNombre.setText(nuevo.getNombre());
            jtxApellido.setText(nuevo.getApellidos());
            jtxRFC.setText(nuevo.getRfc());
            jtxTelefono.setText(String.valueOf(nuevo.getTelefono()));
            jtxCalleNumero.setText(nuevo.getCalleNumero());
            jtxCiudad.setText(nuevo.getCiudad());
            jtxCodigoPostal.setText(String.valueOf(nuevo.getCodigoPostal()));
            jtxColonia.setText(nuevo.getColonia());
            jtxDelegacion.setText(nuevo.getDelegacionMunicipio());


            jbAceptar.setText("Editar");
        }


        if (iEstatus == NUEVO) {
            jtxNombre.setEnabled(true);
            jtxApellido.setEnabled(true);
            jtxRFC.setEnabled(true);
            jtxTelefono.setEnabled(true);
            jtxCalleNumero.setEnabled(true);
            jtxCiudad.setEnabled(true);
            jtxCodigoPostal.setEnabled(true);
            jtxColonia.setEnabled(true);
            jtxDelegacion.setEnabled(true);
            jbAceptar.setText("Agregar");
            limpiaForma();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jbAceptar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jtxNombre = new javax.swing.JTextField();
        jtxApellido = new javax.swing.JTextField();
        jtxRFC = new javax.swing.JTextField();
        jtxCalleNumero = new javax.swing.JTextField();
        jtxColonia = new javax.swing.JTextField();
        jtxDelegacion = new javax.swing.JTextField();
        jtxCiudad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtxTelefono = new javax.swing.JTextField();
        jtxCodigoPostal = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agregar Cliente");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellido");

        jLabel3.setText("RFC");

        jLabel4.setText("Calle y Numero");

        jLabel5.setText("Colonia");

        jLabel6.setText("Codigo Postal");

        jLabel7.setText("Delegación/Municipio");

        jLabel8.setText("Ciudad");

        jbAceptar.setText("Agregar");
        jbAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAceptarActionPerformed(evt);
            }
        });

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jLabel9.setText("Telefono");

        jtxTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxTelefonoActionPerformed(evt);
            }
        });
        jtxTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxTelefonoFocusLost(evt);
            }
        });

        jtxCodigoPostal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxCodigoPostalActionPerformed(evt);
            }
        });
        jtxCodigoPostal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxCodigoPostalFocusLost(evt);
            }
        });

        jMenu1.setText("Archivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Agregar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Acerca");

        jMenuItem2.setText("Ayuda");
        jMenu2.add(jMenuItem2);

        jMenuItem4.setText("Acerca...");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxRFC, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxCalleNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtxDelegacion, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtxColonia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtxCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jbAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtxTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addComponent(jtxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxRFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxCalleNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtxDelegacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtxTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtxCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAceptarActionPerformed
        switch (iEstatus) {
            case NUEVO:
                estado();
                desborde();
                if (bEstado == true) {
                    insertaCliente();

                }
                break;
            case EDITAR:
                modificaCliente();
                JOptionPane.showMessageDialog(this, "Datos Guardados con éxito", "", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                break;
            case CONSULTAR:
                if (frmPass == null) {
                    frmPass = new Pass(this,1);
                }
                frmPass.limpiaFrame();
                frmPass.setVisible(true);
                frmPass.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                frmPass.setAlwaysOnTop(true);
                frmPass.setLocationRelativeTo(this);
                break;
        }
}//GEN-LAST:event_jbAceptarActionPerformed

    @Override
    public void cbPasswprd() {
        jtxNombre.setEnabled(true);
        jtxApellido.setEnabled(true);
        jtxRFC.setEnabled(true);
        jtxTelefono.setEnabled(true);
        jtxCalleNumero.setEnabled(true);
        jtxCiudad.setEnabled(true);
        jtxCodigoPostal.setEnabled(true);
        jtxColonia.setEnabled(true);
        jtxDelegacion.setEnabled(true);
        iEstatus = EDITAR;
        jbAceptar.setText("Guardar");
    }

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        this.dispose();
}//GEN-LAST:event_jbSalirActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        estado();
        desborde();
        if (bEstado == true) {
            insertaCliente();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void jtxCodigoPostalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxCodigoPostalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxCodigoPostalActionPerformed

    private void jtxTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxTelefonoActionPerformed

    private void jtxCodigoPostalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxCodigoPostalFocusLost
        BigDecimal bdCantidad = null;

        if (!jtxCodigoPostal.getText().equals("")) {
            try {
                bdCantidad = new BigDecimal(jtxCodigoPostal.getText());

            } catch (Exception exception) {
                JOptionPane.showMessageDialog(this, "El Codigo Postal debe de ser numerico", "Error", JOptionPane.ERROR_MESSAGE);
                jtxCodigoPostal.setText("");
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_jtxCodigoPostalFocusLost

    private void jtxTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxTelefonoFocusLost
        BigDecimal bdCantidad = null;

        if (!jtxTelefono.getText().equals("")) {
            try {
                bdCantidad = new BigDecimal(jtxTelefono.getText());

            } catch (Exception exception) {
                JOptionPane.showMessageDialog(this, "El Telefono debe de ser numerico", "Error", JOptionPane.ERROR_MESSAGE);
                jtxTelefono.setText("");
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_jtxTelefonoFocusLost

    public void insertaCliente() {
        System.out.println("inserta cliente:");
        nuevo = new Clientes();
        ServicioCliente srvCliente = new ServicioCliente();



        String strClientes;
        List<Clientes> lista;

        if (bEstado == true) {
            strClientes = jtxRFC.getText();
            lista = srvCliente.obtieneClientes(strClientes);
            if (lista != null) {
                if (lista.isEmpty()) {
                    insertaClienteReviso();
                } else {
                    JOptionPane.showMessageDialog(this, "El RFC ya exciste", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                insertaClienteReviso();
            }
        }

        srvCliente.insertaCliente(nuevo);

        limpiaForma();

    }
    public void insertaClienteReviso(){
        nuevo.setNombre(jtxNombre.getText());
        nuevo.setApellidos(jtxApellido.getText());
        nuevo.setRfc(jtxRFC.getText());
        nuevo.setCalleNumero(jtxCalleNumero.getText());
        nuevo.setColonia(jtxColonia.getText());
        nuevo.setCodigoPostal(jtxCodigoPostal.getText());
        nuevo.setDelegacionMunicipio(jtxDelegacion.getText());
        nuevo.setTelefono(jtxTelefono.getText());
        nuevo.setCiudad(jtxCiudad.getText());
        nuevo.setExportado(Character.valueOf('N'));
    }

    public void modificaCliente() {
        System.out.println("inserta cliente:");

        nuevo.setNombre(jtxNombre.getText());
        nuevo.setApellidos(jtxApellido.getText());
        nuevo.setRfc(jtxRFC.getText());
        nuevo.setCalleNumero(jtxCalleNumero.getText());
        nuevo.setColonia(jtxColonia.getText());
        nuevo.setCodigoPostal(jtxCodigoPostal.getText());
        nuevo.setDelegacionMunicipio(jtxDelegacion.getText());
        nuevo.setTelefono(jtxTelefono.getText());
        nuevo.setCiudad(jtxCiudad.getText());

        ServicioCliente servicioCliente = new ServicioCliente();
        servicioCliente.modificaCliente(nuevo);

        limpiaForma();
    }

    private void limpiaForma() {
        jtxNombre.setText("");
        jtxApellido.setText("");
        jtxRFC.setText("");
        jtxTelefono.setText("");
        jtxCalleNumero.setText("");
        jtxCiudad.setText("");
        jtxCodigoPostal.setText("");
        jtxColonia.setText("");
        jtxDelegacion.setText("");
    }

    public void desborde() {
        StringBuilder sbError = new StringBuilder("");
        boolean bEntra = false;


        if (jtxNombre.getText().length() > 20) {
            sbError.append("El campo Nombre solo acepta 20 caracteres\n");
            bEntra = true;
        }
        if (jtxApellido.getText().length() > 50) {
            sbError.append("El campo Apellido solo acepta 50 caracteres\n");
            bEntra = true;

        }
        if (jtxRFC.getText().length() > 13) {
            sbError.append("El campo RFC solo acepta 13 caracteres \n");
            bEntra = true;
        }
        if (jtxCalleNumero.getText().length() > 50) {
            sbError.append("El campo Calle y numero solo acepta 50 caracteres\n");
            bEntra = true;
        }
        if (jtxColonia.getText().length() > 20) {
            sbError.append("El campo Colonia solo acepta 20 caracteres\n");
            bEntra = true;
        }
        if (jtxCodigoPostal.getText().length() > 7) {
            sbError.append("El campo Codigo postal solo acepta 7 caracteres\n");
            bEntra = true;
        }
        if (jtxDelegacion.getText().length() > 20) {
            sbError.append("El campo Delegacion solo acepta 20 caracteres\n");
            bEntra = true;
        }
        if (jtxCiudad.getText().length() > 20) {
            sbError.append("El campo Ciudad solo acepta 20 caracteres\n");
            bEntra = true;
        }
        if (jtxTelefono.getText().length() > 15) {
            sbError.append("El campo Telefono solo acepta 15 caracteres\n");
            bEntra = true;
        }

        if (bEntra == true) {
            JOptionPane.showMessageDialog(this, "" + sbError, "Demasiados caracteres", JOptionPane.ERROR_MESSAGE);
            bEstado = false;
        }

    }

    public void estado() {
        String sNombre;
        String sApellido;
        String sRfc;
        String sCalle;
        String sColonia;
        String sCodigo;
        String sTel;
        String sCiudad;
        StringBuilder sbFaltantes = new StringBuilder("");
        boolean bFaltan = false;

        sNombre = jtxNombre.getText();
        sApellido = jtxApellido.getText();
        sRfc = jtxRFC.getText();
        sCalle = jtxCalleNumero.getText();
        sColonia = jtxColonia.getText();
        sCodigo = jtxCodigoPostal.getText();

        if (jtxTelefono.getText() != null) {
            sTel = jtxTelefono.getText();
        } else {
            sTel = "";
        }

        sCiudad = jtxCiudad.getText();

        if (sNombre.equals("")) {
            sbFaltantes.append("Nombre \n");
            bFaltan = true;
        }
        if (sApellido.equals("")) {
            sbFaltantes.append("Apellido\n");
            bFaltan = true;
        }
        if (sRfc.equals("")) {
            sbFaltantes.append("RFC\n");
            bFaltan = true;
        }
        if (sCalle.equals("")) {
            sbFaltantes.append("Calle\n");
            bFaltan = true;
        }
        if (sColonia.equals("")) {
            sbFaltantes.append("Colonia\n");
            bFaltan = true;
        }
        if (sCodigo.equals("")) {
            sbFaltantes.append("Codigo Postal\n");
            bFaltan = true;
        }
        if (sTel.equals("")) {
            sbFaltantes.append("Teléfono\n");
            bFaltan = true;
        }
        if (sCiudad.equals("")) {
            sbFaltantes.append("Ciudad\n");
            bFaltan = true;
        }
        if (bFaltan == true) {
            JOptionPane.showMessageDialog(this, "Los campos:\n" + sbFaltantes + "Son requeridos", "Campos faltantes", JOptionPane.ERROR_MESSAGE);
            bEstado = false;
        } else {

            bEstado = true;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JButton jbAceptar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JTextField jtxApellido;
    private javax.swing.JTextField jtxCalleNumero;
    private javax.swing.JTextField jtxCiudad;
    private javax.swing.JTextField jtxCodigoPostal;
    private javax.swing.JTextField jtxColonia;
    private javax.swing.JTextField jtxDelegacion;
    private javax.swing.JTextField jtxNombre;
    private javax.swing.JTextField jtxRFC;
    private javax.swing.JTextField jtxTelefono;
    // End of variables declaration//GEN-END:variables

}
