/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package mx.com.altadatosgenerales;

import javax.swing.JPanel;

public final class AltaDatosGeneralesVisualPanel1 extends JPanel {

    /** Creates new form AltaDatosGeneralesVisualPanel1 */
    public AltaDatosGeneralesVisualPanel1() {
        initComponents();
    }

    @Override
    public String getName() {
        return "Datos de la Escuela";
    }

    public String getNombreEscuela(){
        return this.jtfNombreEscuela.getText();
    }

    public String getDireccion(){
        return this.jtfDireccion.getText();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfNombreEscuela = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfDireccion = new javax.swing.JTextField();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(AltaDatosGeneralesVisualPanel1.class, "AltaDatosGeneralesVisualPanel1.jLabel1.text")); // NOI18N

        jtfNombreEscuela.setText(org.openide.util.NbBundle.getMessage(AltaDatosGeneralesVisualPanel1.class, "AltaDatosGeneralesVisualPanel1.jtfNombreEscuela.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(AltaDatosGeneralesVisualPanel1.class, "AltaDatosGeneralesVisualPanel1.jLabel2.text")); // NOI18N

        jtfDireccion.setText(org.openide.util.NbBundle.getMessage(AltaDatosGeneralesVisualPanel1.class, "AltaDatosGeneralesVisualPanel1.jtfDireccion.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                    .addComponent(jtfNombreEscuela, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNombreEscuela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(232, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jtfDireccion;
    private javax.swing.JTextField jtfNombreEscuela;
    // End of variables declaration//GEN-END:variables
}

