package mx.com.analisispreciosmercado.conf;

// Generated 12-feb-2009 0:14:27 by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ConfiguracionSplitId generated by hbm2java
 */
@Embeddable
public class ConfiguracionSplitId implements java.io.Serializable {

	private String emisora;
	private String serie;
	private Date fechaAlta;

	public ConfiguracionSplitId() {
	}

	public ConfiguracionSplitId(String emisora, String serie, Date fechaAlta) {
		this.emisora = emisora;
		this.serie = serie;
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "emisora", nullable = false, length = 25)
	public String getEmisora() {
		return this.emisora;
	}

	public void setEmisora(String emisora) {
		this.emisora = emisora;
	}

	@Column(name = "serie", nullable = false, length = 10)
	public String getSerie() {
		return this.serie;
	}

	public void setSerie(String serie) {
		this.serie = serie;
	}

	@Column(name = "fecha_alta", nullable = false, length = 13)
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ConfiguracionSplitId))
			return false;
		ConfiguracionSplitId castOther = (ConfiguracionSplitId) other;

		return ((this.getEmisora() == castOther.getEmisora()) || (this
				.getEmisora() != null
				&& castOther.getEmisora() != null && this.getEmisora().equals(
				castOther.getEmisora())))
				&& ((this.getSerie() == castOther.getSerie()) || (this
						.getSerie() != null
						&& castOther.getSerie() != null && this.getSerie()
						.equals(castOther.getSerie())))
				&& ((this.getFechaAlta() == castOther.getFechaAlta()) || (this
						.getFechaAlta() != null
						&& castOther.getFechaAlta() != null && this
						.getFechaAlta().equals(castOther.getFechaAlta())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getEmisora() == null ? 0 : this.getEmisora().hashCode());
		result = 37 * result
				+ (getSerie() == null ? 0 : this.getSerie().hashCode());
		result = 37 * result
				+ (getFechaAlta() == null ? 0 : this.getFechaAlta().hashCode());
		return result;
	}

}
