package mx.com.analisispreciosmercado.conf;

// Generated 12-feb-2009 0:14:27 by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IndicesIntraDiaId generated by hbm2java
 */
@Embeddable
public class IndicesIntraDiaId implements java.io.Serializable {

	private Date fecha;
	private String indice;
	private Integer idCarga;

	public IndicesIntraDiaId() {
	}

	public IndicesIntraDiaId(Date fecha, String indice, Integer idCarga) {
		this.fecha = fecha;
		this.indice = indice;
		this.idCarga = idCarga;
	}

	@Column(name = "fecha", nullable = false, length = 29)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "indice", nullable = false, length = 25)
	public String getIndice() {
		return this.indice;
	}

	public void setIndice(String indice) {
		this.indice = indice;
	}

	@Column(name = "id_carga", nullable = false)
	public Integer getIdCarga() {
		return this.idCarga;
	}

	public void setIdCarga(Integer idCarga) {
		this.idCarga = idCarga;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IndicesIntraDiaId))
			return false;
		IndicesIntraDiaId castOther = (IndicesIntraDiaId) other;

		return ((this.getFecha() == castOther.getFecha()) || (this.getFecha() != null
				&& castOther.getFecha() != null && this.getFecha().equals(
				castOther.getFecha())))
				&& ((this.getIndice() == castOther.getIndice()) || (this
						.getIndice() != null
						&& castOther.getIndice() != null && this.getIndice()
						.equals(castOther.getIndice())))
				&& ((this.getIdCarga() == castOther.getIdCarga()) || (this
						.getIdCarga() != null
						&& castOther.getIdCarga() != null && this.getIdCarga()
						.equals(castOther.getIdCarga())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getFecha() == null ? 0 : this.getFecha().hashCode());
		result = 37 * result
				+ (getIndice() == null ? 0 : this.getIndice().hashCode());
		result = 37 * result
				+ (getIdCarga() == null ? 0 : this.getIdCarga().hashCode());
		return result;
	}

}
