package mx.com.analisispreciosmercado.conf;

// Generated 10/12/2008 06:03:50 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IndicesId generated by hbm2java
 */
@Embeddable
public class IndicesId implements java.io.Serializable {

	private Date fecha;
	private String indice;

	public IndicesId() {
	}

	public IndicesId(Date fecha, String indice) {
		this.fecha = fecha;
		this.indice = indice;
	}

	@Column(name = "fecha", nullable = false, length = 13)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "indice", nullable = false, length = 25)
	public String getIndice() {
		return this.indice;
	}

	public void setIndice(String indice) {
		this.indice = indice;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IndicesId))
			return false;
		IndicesId castOther = (IndicesId) other;

		return ((this.getFecha() == castOther.getFecha()) || (this.getFecha() != null
				&& castOther.getFecha() != null && this.getFecha().equals(
				castOther.getFecha())))
				&& ((this.getIndice() == castOther.getIndice()) || (this
						.getIndice() != null
						&& castOther.getIndice() != null && this.getIndice()
						.equals(castOther.getIndice())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getFecha() == null ? 0 : this.getFecha().hashCode());
		result = 37 * result
				+ (getIndice() == null ? 0 : this.getIndice().hashCode());
		return result;
	}

}
