package mx.com.analisispreciosmercado.conf;

// Generated 12-feb-2009 0:14:27 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * IpConfTablasHtmlParsear generated by hbm2java
 */
@Entity
@Table(name = "ip_conf_tablas_html_parsear", schema = "public")
public class IpConfTablasHtmlParsear implements java.io.Serializable {

	private Integer idTabla;
	private String nombreTabla;
	private char formatoTabla;
	private String objetoRegresar;
	private Set<CiConfLinks> ciConfLinkses = new HashSet<CiConfLinks>(0);
	private Set<IpConfPropiedadesTabla> ipConfPropiedadesTablas = new HashSet<IpConfPropiedadesTabla>(
			0);

	public IpConfTablasHtmlParsear() {
	}

	public IpConfTablasHtmlParsear(Integer idTabla, String nombreTabla,
			char formatoTabla, String objetoRegresar) {
		this.idTabla = idTabla;
		this.nombreTabla = nombreTabla;
		this.formatoTabla = formatoTabla;
		this.objetoRegresar = objetoRegresar;
	}

	public IpConfTablasHtmlParsear(Integer idTabla, String nombreTabla,
			char formatoTabla, String objetoRegresar,
			Set<CiConfLinks> ciConfLinkses,
			Set<IpConfPropiedadesTabla> ipConfPropiedadesTablas) {
		this.idTabla = idTabla;
		this.nombreTabla = nombreTabla;
		this.formatoTabla = formatoTabla;
		this.objetoRegresar = objetoRegresar;
		this.ciConfLinkses = ciConfLinkses;
		this.ipConfPropiedadesTablas = ipConfPropiedadesTablas;
	}

	@Id
	@Column(name = "id_tabla", unique = true, nullable = false)
	public Integer getIdTabla() {
		return this.idTabla;
	}

	public void setIdTabla(Integer idTabla) {
		this.idTabla = idTabla;
	}

	@Column(name = "nombre_tabla", nullable = false, length = 100)
	public String getNombreTabla() {
		return this.nombreTabla;
	}

	public void setNombreTabla(String nombreTabla) {
		this.nombreTabla = nombreTabla;
	}

	@Column(name = "formato_tabla", nullable = false, length = 1)
	public char getFormatoTabla() {
		return this.formatoTabla;
	}

	public void setFormatoTabla(char formatoTabla) {
		this.formatoTabla = formatoTabla;
	}

	@Column(name = "objeto_regresar", nullable = false, length = 500)
	public String getObjetoRegresar() {
		return this.objetoRegresar;
	}

	public void setObjetoRegresar(String objetoRegresar) {
		this.objetoRegresar = objetoRegresar;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "ipConfTablasHtmlParsear")
	public Set<CiConfLinks> getCiConfLinkses() {
		return this.ciConfLinkses;
	}

	public void setCiConfLinkses(Set<CiConfLinks> ciConfLinkses) {
		this.ciConfLinkses = ciConfLinkses;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "ipConfTablasHtmlParsear")
	public Set<IpConfPropiedadesTabla> getIpConfPropiedadesTablas() {
		return this.ipConfPropiedadesTablas;
	}

	public void setIpConfPropiedadesTablas(
			Set<IpConfPropiedadesTabla> ipConfPropiedadesTablas) {
		this.ipConfPropiedadesTablas = ipConfPropiedadesTablas;
	}

}
