package mx.com.analisispreciosmercado.conf;

// Generated 12-feb-2009 0:14:27 by Hibernate Tools 3.2.1.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * IpConfPropiedadesTabla generated by hbm2java
 */
@Entity
@Table(name = "ip_conf_propiedades_tabla", schema = "ADMIN")
public class IpConfPropiedadesTabla implements java.io.Serializable {

	private IpConfPropiedadesTablaId id;
	private IpConfTablasHtmlParsear ipConfTablasHtmlParsear;
	private String nombrePropiedad;
	private String claseHtml;
	private String nombrePropiedadObjeto;
	private Character tipoDato;

	public IpConfPropiedadesTabla() {
	}

	public IpConfPropiedadesTabla(IpConfPropiedadesTablaId id,
			IpConfTablasHtmlParsear ipConfTablasHtmlParsear,
			String nombrePropiedad, String nombrePropiedadObjeto) {
		this.id = id;
		this.ipConfTablasHtmlParsear = ipConfTablasHtmlParsear;
		this.nombrePropiedad = nombrePropiedad;
		this.nombrePropiedadObjeto = nombrePropiedadObjeto;
	}

	public IpConfPropiedadesTabla(IpConfPropiedadesTablaId id,
			IpConfTablasHtmlParsear ipConfTablasHtmlParsear,
			String nombrePropiedad, String claseHtml,
			String nombrePropiedadObjeto, Character tipoDato) {
		this.id = id;
		this.ipConfTablasHtmlParsear = ipConfTablasHtmlParsear;
		this.nombrePropiedad = nombrePropiedad;
		this.claseHtml = claseHtml;
		this.nombrePropiedadObjeto = nombrePropiedadObjeto;
		this.tipoDato = tipoDato;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "idTabla", column = @Column(name = "id_tabla", nullable = false)),
			@AttributeOverride(name = "idPropiedadTabla", column = @Column(name = "id_propiedad_tabla", nullable = false)) })
	public IpConfPropiedadesTablaId getId() {
		return this.id;
	}

	public void setId(IpConfPropiedadesTablaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tabla", nullable = false, insertable = false, updatable = false)
	public IpConfTablasHtmlParsear getIpConfTablasHtmlParsear() {
		return this.ipConfTablasHtmlParsear;
	}

	public void setIpConfTablasHtmlParsear(
			IpConfTablasHtmlParsear ipConfTablasHtmlParsear) {
		this.ipConfTablasHtmlParsear = ipConfTablasHtmlParsear;
	}

	@Column(name = "nombre_propiedad", nullable = false, length = 100)
	public String getNombrePropiedad() {
		return this.nombrePropiedad;
	}

	public void setNombrePropiedad(String nombrePropiedad) {
		this.nombrePropiedad = nombrePropiedad;
	}

	@Column(name = "clase_html", length = 100)
	public String getClaseHtml() {
		return this.claseHtml;
	}

	public void setClaseHtml(String claseHtml) {
		this.claseHtml = claseHtml;
	}

	@Column(name = "nombre_propiedad_objeto", nullable = false, length = 100)
	public String getNombrePropiedadObjeto() {
		return this.nombrePropiedadObjeto;
	}

	public void setNombrePropiedadObjeto(String nombrePropiedadObjeto) {
		this.nombrePropiedadObjeto = nombrePropiedadObjeto;
	}

	@Column(name = "tipo_dato", length = 1)
	public Character getTipoDato() {
		return this.tipoDato;
	}

	public void setTipoDato(Character tipoDato) {
		this.tipoDato = tipoDato;
	}

}
