CREATE TABLE SERIES_OPERADAS (
       FECHA DATE NOT NULL
     , EMISORA VARCHAR(25) NOT NULL
     , SERIE VARCHAR(10) NOT NULL
     , HORA TIME
     , ULTIMO NUMERIC(16,2) NOT NULL
     , PPP NUMERIC(16,2)
     , ANTERIOR NUMERIC(16,2) NOT NULL
     , MAXIMO NUMERIC(16,2) NOT NULL
     , MINIMO NUMERIC(16,2) NOT NULL
     , VOLUMEN NUMERIC(12)
     , IMPORTE NUMERIC(16,2)
     , OPERACIONES NUMERIC(6)
     , PUNTOS NUMERIC(8,2)
     , PORCENTAJE NUMERIC(4,2)
     , DIA_HABIL CHAR(1) NOT NULL
     , SPLIT INTEGER NOT NULL
     , VAR_PCT_PRECIO NUMERIC(6,4)
     , VAR_PCT_MAXIMO NUMERIC(6,4) NOT NULL
     , VAR_PCT_MINIMO NUMERIC(6,4) NOT NULL
     , VAR_PCT NUMERIC(6,4) NOT NULL
     , RENDIMIENTO NUMERIC(4,3)
     , IND_BURSATILIDAD NUMERIC(9,6)
     , TIPO_IND_BURSATILIDAD CHAR(1)
     , PRIMARY KEY (FECHA, EMISORA, SERIE)
)
;

CREATE TABLE DIAS_FESTIVOS (
       FECHA DATE NOT NULL
     , DESCRIPCION VARCHAR(200)
     , PRIMARY KEY (FECHA)
)
;

CREATE TABLE CONFIGURACION_SPLIT (
       FECHA_ALTA DATE NOT NULL
     , EMISORA VARCHAR(25) NOT NULL
     , SERIE VARCHAR(10) NOT NULL
     , FECHA_APLICACION DATE
     , SPLIT INTEGER NOT NULL
     , PRIMARY KEY (EMISORA, SERIE, FECHA_ALTA)
)
;

CREATE TABLE INDICES (
       FECHA DATE NOT NULL
     , INDICE VARCHAR(25) NOT NULL
     , ULTIMO NUMERIC(16,2) NOT NULL
     , HORA TIME
     , ANTERIOR NUMERIC(16,2) NOT NULL
     , PORCENTAJE NUMERIC(4,2)
     , PUNTOS NUMERIC(8,2)
     , MAXIMO NUMERIC(16,2) NOT NULL
     , HORA_MAXIMO TIME
     , MINIMO NUMERIC(16,2) NOT NULL
     , HORA_MINIMO TIME
     , DIA_HABIL CHAR(1) NOT NULL
     , VAR_PCT_ULTIMO NUMERIC(6,4)
     , VAR_PCT_MAXIMO NUMERIC(6,4) NOT NULL
     , VAR_PCT_MINIMO NUMERIC(6,4) NOT NULL
     , VAR_PCT NUMERIC(6,4) NOT NULL
     , RENDIMIENTO NUMERIC(4,3)
     , PRIMARY KEY (FECHA, INDICE)
)
;

CREATE TABLE SERIES_OPERADAS_INTRA_DIA (
       FECHA DATE NOT NULL
     , ID_CARGA INTEGER NOT NULL
     , EMISORA VARCHAR(25) NOT NULL
     , SERIE VARCHAR(10) NOT NULL
     , HORA TIME NOT NULL
     , ULTIMO NUMERIC(16,2) NOT NULL
     , PPP NUMERIC(16,2) NOT NULL
     , ANTERIOR NUMERIC(16,2) NOT NULL
     , MAXIMO NUMERIC(16,2) NOT NULL
     , HORA_MAXIMO TIME NOT NULL
     , MINIMO NUMERIC(16,2) NOT NULL
     , HORA_MINIMO TIME NOT NULL
     , VOLUMEN NUMERIC(12) NOT NULL
     , IMPORTE NUMERIC(16,2) NOT NULL
     , OPERACIONES NUMERIC(6) NOT NULL
     , PUNTOS NUMERIC(8,2) NOT NULL
     , PORCENTAJE NUMERIC(4,2) NOT NULL
     , SPLIT INTEGER NOT NULL
     , VAR_PCT_PRECIO NUMERIC(6,4)
     , VAR_PCT_MAXIMO NUMERIC(6,4)
     , VAR_PCT_MINIMO NUMERIC(6,4)
     , VAR_PCT NUMERIC(6,4)
     , RENDIMIENTO NUMERIC(6,4)
     , PRIMARY KEY (FECHA, ID_CARGA, EMISORA, SERIE)
)
;

CREATE TABLE INDICES_INTRA_DIA (
       FECHA DATE NOT NULL
     , ID_CARGA INTEGER NOT NULL
     , INDICE VARCHAR(25) NOT NULL
     , ULTIMO NUMERIC(16,2) NOT NULL
     , HORA TIME
     , ANTERIOR NUMERIC(16,2) NOT NULL
     , PORCENTAJE NUMERIC(4,2)
     , PUNTOS NUMERIC(8,2)
     , MAXIMO NUMERIC(16,2) NOT NULL
     , HORA_MAXIMO TIME
     , MINIMO NUMERIC(16,2) NOT NULL
     , HORA_MINIMO TIME
     , VAR_PCT_ULTIMO NUMERIC(6,4)
     , VAR_PCT_MAXIMO NUMERIC(6,4)
     , VAR_PCT_MINIMO NUMERIC(6,4)
     , VAR_PCT NUMERIC(6,4)
     , RENDIMIENTO NUMERIC(6,4)
     , PRIMARY KEY (FECHA, ID_CARGA, INDICE)
)
;

CREATE TABLE CI_CONF_LINKS (
       ID_CONF INTEGER NOT NULL
     , LINK VARCHAR(200) NOT NULL
     , ID_TABLA INTEGER NOT NULL
     , PRIMARY KEY (ID_CONF)
     , CONSTRAINT FK_CI_CONF_LINKS_1 FOREIGN KEY (ID_TABLA)
                  REFERENCES ip_conf_tablas_html_parsear (id_tabla)
)
;

