CREATE TABLE IP_CONF_TABLAS_HTML_PARSEAR (
       ID_TABLA INTEGER NOT NULL
     , NOMBRE_TABLA VARCHAR(100) NOT NULL
     , FORMATO_TABLA CHAR(1) NOT NULL
     , OBJETO_REGRESAR VARCHAR(500) NOT NULL
);
CREATE INDEX IX_IP_CONF_TABLAS_HTML_PARSEAR ON IP_CONF_TABLAS_HTML_PARSEAR (ID_TABLA);

CREATE TABLE IP_CONF_PROPIEDADES_TABLA (
       ID_TABLA INTEGER NOT NULL
     , ID_PROPIEDAD_TABLA INTEGER NOT NULL
     , NOMBRE_PROPIEDAD VARCHAR(100) NOT NULL
     , CLASE_HTML VARCHAR(100)
     , NOMBRE_PROPIEDAD_OBJETO VARCHAR(100) NOT NULL
     , TIPO_DATO CHAR(1)
);
CREATE INDEX IX_IP_CONF_PROPIEDADES_TABLA_1 ON IP_CONF_PROPIEDADES_TABLA (ID_TABLA, ID_PROPIEDAD_TABLA);

ALTER TABLE IP_CONF_TABLAS_HTML_PARSEAR
  ADD CONSTRAINT PK_IP_CONF_TABLAS_HTML_PARSEAR
      PRIMARY KEY (ID_TABLA);

ALTER TABLE IP_CONF_PROPIEDADES_TABLA
  ADD CONSTRAINT PK_IP_CONF_PROPIEDADES_TABLA
      PRIMARY KEY (ID_TABLA, ID_PROPIEDAD_TABLA);

ALTER TABLE IP_CONF_PROPIEDADES_TABLA
  ADD CONSTRAINT FK_PROPIEDADES_1
      FOREIGN KEY (ID_TABLA)
      REFERENCES IP_CONF_TABLAS_HTML_PARSEAR (ID_TABLA);

