package mx.com.analisispreciosmercado.conf;

// Generated 12-feb-2009 0:14:27 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IndicesIntraDia generated by hbm2java
 */
@Entity
@Table(name = "indices_intra_dia", schema = "ADMIN")
public class IndicesIntraDia implements java.io.Serializable {

	private IndicesIntraDiaId id;
	private BigDecimal ultimo;
	private Date hora;
	private BigDecimal anterior;
	private BigDecimal porcentaje;
	private BigDecimal puntos;
	private BigDecimal maximo;
	private Date horaMaximo;
	private BigDecimal minimo;
	private Date horaMinimo;
	private BigDecimal varPctUltimo;
	private BigDecimal varPctMaximo;
	private BigDecimal varPctMinimo;
	private BigDecimal varPct;
	private BigDecimal rendimiento;

	public IndicesIntraDia() {
	}

	public IndicesIntraDia(IndicesIntraDiaId id, BigDecimal ultimo,
			BigDecimal anterior, BigDecimal maximo, BigDecimal minimo) {
		this.id = id;
		this.ultimo = ultimo;
		this.anterior = anterior;
		this.maximo = maximo;
		this.minimo = minimo;
	}

	public IndicesIntraDia(IndicesIntraDiaId id, BigDecimal ultimo, Date hora,
			BigDecimal anterior, BigDecimal porcentaje, BigDecimal puntos,
			BigDecimal maximo, Date horaMaximo, BigDecimal minimo,
			Date horaMinimo, BigDecimal varPctUltimo, BigDecimal varPctMaximo,
			BigDecimal varPctMinimo, BigDecimal varPct, BigDecimal rendimiento) {
		this.id = id;
		this.ultimo = ultimo;
		this.hora = hora;
		this.anterior = anterior;
		this.porcentaje = porcentaje;
		this.puntos = puntos;
		this.maximo = maximo;
		this.horaMaximo = horaMaximo;
		this.minimo = minimo;
		this.horaMinimo = horaMinimo;
		this.varPctUltimo = varPctUltimo;
		this.varPctMaximo = varPctMaximo;
		this.varPctMinimo = varPctMinimo;
		this.varPct = varPct;
		this.rendimiento = rendimiento;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "fecha", column = @Column(name = "fecha", nullable = false, length = 29)),
			@AttributeOverride(name = "indice", column = @Column(name = "indice", nullable = false, length = 25)),
			@AttributeOverride(name = "idCarga", column = @Column(name = "id_carga", nullable = false)) })
	public IndicesIntraDiaId getId() {
		return this.id;
	}

	public void setId(IndicesIntraDiaId id) {
		this.id = id;
	}

	@Column(name = "ultimo", nullable = false, precision = 16)
	public BigDecimal getUltimo() {
		return this.ultimo;
	}

	public void setUltimo(BigDecimal ultimo) {
		this.ultimo = ultimo;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora", length = 15)
	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	@Column(name = "anterior", nullable = false, precision = 16)
	public BigDecimal getAnterior() {
		return this.anterior;
	}

	public void setAnterior(BigDecimal anterior) {
		this.anterior = anterior;
	}

	@Column(name = "porcentaje", precision = 4)
	public BigDecimal getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(BigDecimal porcentaje) {
		this.porcentaje = porcentaje;
	}

	@Column(name = "puntos", precision = 8)
	public BigDecimal getPuntos() {
		return this.puntos;
	}

	public void setPuntos(BigDecimal puntos) {
		this.puntos = puntos;
	}

	@Column(name = "maximo", nullable = false, precision = 16)
	public BigDecimal getMaximo() {
		return this.maximo;
	}

	public void setMaximo(BigDecimal maximo) {
		this.maximo = maximo;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_maximo", length = 15)
	public Date getHoraMaximo() {
		return this.horaMaximo;
	}

	public void setHoraMaximo(Date horaMaximo) {
		this.horaMaximo = horaMaximo;
	}

	@Column(name = "minimo", nullable = false, precision = 16)
	public BigDecimal getMinimo() {
		return this.minimo;
	}

	public void setMinimo(BigDecimal minimo) {
		this.minimo = minimo;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_minimo", length = 15)
	public Date getHoraMinimo() {
		return this.horaMinimo;
	}

	public void setHoraMinimo(Date horaMinimo) {
		this.horaMinimo = horaMinimo;
	}

	@Column(name = "var_pct_ultimo", precision = 6, scale = 4)
	public BigDecimal getVarPctUltimo() {
		return this.varPctUltimo;
	}

	public void setVarPctUltimo(BigDecimal varPctUltimo) {
		this.varPctUltimo = varPctUltimo;
	}

	@Column(name = "var_pct_maximo", precision = 6, scale = 4)
	public BigDecimal getVarPctMaximo() {
		return this.varPctMaximo;
	}

	public void setVarPctMaximo(BigDecimal varPctMaximo) {
		this.varPctMaximo = varPctMaximo;
	}

	@Column(name = "var_pct_minimo", precision = 6, scale = 4)
	public BigDecimal getVarPctMinimo() {
		return this.varPctMinimo;
	}

	public void setVarPctMinimo(BigDecimal varPctMinimo) {
		this.varPctMinimo = varPctMinimo;
	}

	@Column(name = "var_pct", precision = 6, scale = 4)
	public BigDecimal getVarPct() {
		return this.varPct;
	}

	public void setVarPct(BigDecimal varPct) {
		this.varPct = varPct;
	}

	@Column(name = "rendimiento", precision = 6, scale = 4)
	public BigDecimal getRendimiento() {
		return this.rendimiento;
	}

	public void setRendimiento(BigDecimal rendimiento) {
		this.rendimiento = rendimiento;
	}

}
