package mx.com.analisispreciosmercado.conf;

// Generated 12-feb-2009 0:14:27 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Indices generated by hbm2java
 */
@Entity
@Table(name = "indices", schema = "public")
public class Indices implements java.io.Serializable {

	private IndicesId id;
	private BigDecimal ultimo;
	private Date hora;
	private BigDecimal anterior;
	private BigDecimal porcentaje;
	private BigDecimal puntos;
	private BigDecimal maximo;
	private Date horaMaximo;
	private BigDecimal minimo;
	private Date horaMinimo;
	private char diaHabil;
	private BigDecimal varPctUltimo;
	private BigDecimal varPctMaximo;
	private BigDecimal varPctMinimo;
	private BigDecimal varPct;
	private BigDecimal rendimiento;

	public Indices() {
	}

	public Indices(IndicesId id, BigDecimal ultimo, BigDecimal anterior,
			BigDecimal maximo, BigDecimal minimo, char diaHabil,
			BigDecimal varPctMaximo, BigDecimal varPctMinimo, BigDecimal varPct) {
		this.id = id;
		this.ultimo = ultimo;
		this.anterior = anterior;
		this.maximo = maximo;
		this.minimo = minimo;
		this.diaHabil = diaHabil;
		this.varPctMaximo = varPctMaximo;
		this.varPctMinimo = varPctMinimo;
		this.varPct = varPct;
	}

	public Indices(IndicesId id, BigDecimal ultimo, Date hora,
			BigDecimal anterior, BigDecimal porcentaje, BigDecimal puntos,
			BigDecimal maximo, Date horaMaximo, BigDecimal minimo,
			Date horaMinimo, char diaHabil, BigDecimal varPctUltimo,
			BigDecimal varPctMaximo, BigDecimal varPctMinimo,
			BigDecimal varPct, BigDecimal rendimiento) {
		this.id = id;
		this.ultimo = ultimo;
		this.hora = hora;
		this.anterior = anterior;
		this.porcentaje = porcentaje;
		this.puntos = puntos;
		this.maximo = maximo;
		this.horaMaximo = horaMaximo;
		this.minimo = minimo;
		this.horaMinimo = horaMinimo;
		this.diaHabil = diaHabil;
		this.varPctUltimo = varPctUltimo;
		this.varPctMaximo = varPctMaximo;
		this.varPctMinimo = varPctMinimo;
		this.varPct = varPct;
		this.rendimiento = rendimiento;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "fecha", column = @Column(name = "fecha", nullable = false, length = 13)),
			@AttributeOverride(name = "indice", column = @Column(name = "indice", nullable = false, length = 25)) })
	public IndicesId getId() {
		return this.id;
	}

	public void setId(IndicesId id) {
		this.id = id;
	}

	@Column(name = "ultimo", nullable = false, precision = 16)
	public BigDecimal getUltimo() {
		return this.ultimo;
	}

	public void setUltimo(BigDecimal ultimo) {
		this.ultimo = ultimo;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora", length = 15)
	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	@Column(name = "anterior", nullable = false, precision = 16)
	public BigDecimal getAnterior() {
		return this.anterior;
	}

	public void setAnterior(BigDecimal anterior) {
		this.anterior = anterior;
	}

	@Column(name = "porcentaje", precision = 4)
	public BigDecimal getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(BigDecimal porcentaje) {
		this.porcentaje = porcentaje;
	}

	@Column(name = "puntos", precision = 8)
	public BigDecimal getPuntos() {
		return this.puntos;
	}

	public void setPuntos(BigDecimal puntos) {
		this.puntos = puntos;
	}

	@Column(name = "maximo", nullable = false, precision = 16)
	public BigDecimal getMaximo() {
		return this.maximo;
	}

	public void setMaximo(BigDecimal maximo) {
		this.maximo = maximo;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_maximo", length = 15)
	public Date getHoraMaximo() {
		return this.horaMaximo;
	}

	public void setHoraMaximo(Date horaMaximo) {
		this.horaMaximo = horaMaximo;
	}

	@Column(name = "minimo", nullable = false, precision = 16)
	public BigDecimal getMinimo() {
		return this.minimo;
	}

	public void setMinimo(BigDecimal minimo) {
		this.minimo = minimo;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_minimo", length = 15)
	public Date getHoraMinimo() {
		return this.horaMinimo;
	}

	public void setHoraMinimo(Date horaMinimo) {
		this.horaMinimo = horaMinimo;
	}

	@Column(name = "dia_habil", nullable = false, length = 1)
	public char getDiaHabil() {
		return this.diaHabil;
	}

	public void setDiaHabil(char diaHabil) {
		this.diaHabil = diaHabil;
	}

	@Column(name = "var_pct_ultimo", precision = 6, scale = 4)
	public BigDecimal getVarPctUltimo() {
		return this.varPctUltimo;
	}

	public void setVarPctUltimo(BigDecimal varPctUltimo) {
		this.varPctUltimo = varPctUltimo;
	}

	@Column(name = "var_pct_maximo", nullable = false, precision = 6, scale = 4)
	public BigDecimal getVarPctMaximo() {
		return this.varPctMaximo;
	}

	public void setVarPctMaximo(BigDecimal varPctMaximo) {
		this.varPctMaximo = varPctMaximo;
	}

	@Column(name = "var_pct_minimo", nullable = false, precision = 6, scale = 4)
	public BigDecimal getVarPctMinimo() {
		return this.varPctMinimo;
	}

	public void setVarPctMinimo(BigDecimal varPctMinimo) {
		this.varPctMinimo = varPctMinimo;
	}

	@Column(name = "var_pct", nullable = false, precision = 6, scale = 4)
	public BigDecimal getVarPct() {
		return this.varPct;
	}

	public void setVarPct(BigDecimal varPct) {
		this.varPct = varPct;
	}

	@Column(name = "rendimiento", precision = 4, scale = 3)
	public BigDecimal getRendimiento() {
		return this.rendimiento;
	}

	public void setRendimiento(BigDecimal rendimiento) {
		this.rendimiento = rendimiento;
	}

}
