package mx.com.analisispreciosmercado.conf;

// Generated 10/12/2008 06:03:50 PM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SeriesOperadasIntraDia generated by hbm2java
 */
@Entity
@Table(name = "series_operadas_intra_dia", schema = "public")
public class SeriesOperadasIntraDia implements java.io.Serializable {

	private SeriesOperadasIntraDiaId id;
	private Date hora;
	private BigDecimal ultimo;
	private BigDecimal ppp;
	private BigDecimal anterior;
	private BigDecimal maximo;
	private Date horaMaximo;
	private BigDecimal minimo;
	private Date horaMinimo;
	private long volumen;
	private BigDecimal importe;
	private int operaciones;
	private BigDecimal puntos;
	private BigDecimal porcentaje;
	private Integer split;
	private BigDecimal varPctPrecio;
	private BigDecimal varPctMaximo;
	private BigDecimal varPctMinimo;
	private BigDecimal varPct;
	private BigDecimal rendimiento;

	public SeriesOperadasIntraDia() {
	}

	public SeriesOperadasIntraDia(SeriesOperadasIntraDiaId id, Date hora,
			BigDecimal ultimo, BigDecimal ppp, BigDecimal anterior,
			BigDecimal maximo, Date horaMaximo, BigDecimal minimo,
			Date horaMinimo, long volumen, BigDecimal importe, int operaciones,
			BigDecimal puntos, BigDecimal porcentaje, Integer split) {
		this.id = id;
		this.hora = hora;
		this.ultimo = ultimo;
		this.ppp = ppp;
		this.anterior = anterior;
		this.maximo = maximo;
		this.horaMaximo = horaMaximo;
		this.minimo = minimo;
		this.horaMinimo = horaMinimo;
		this.volumen = volumen;
		this.importe = importe;
		this.operaciones = operaciones;
		this.puntos = puntos;
		this.porcentaje = porcentaje;
		this.split = split;
	}

	public SeriesOperadasIntraDia(SeriesOperadasIntraDiaId id, Date hora,
			BigDecimal ultimo, BigDecimal ppp, BigDecimal anterior,
			BigDecimal maximo, Date horaMaximo, BigDecimal minimo,
			Date horaMinimo, long volumen, BigDecimal importe, int operaciones,
			BigDecimal puntos, BigDecimal porcentaje, Integer split,
			BigDecimal varPctPrecio, BigDecimal varPctMaximo,
			BigDecimal varPctMinimo, BigDecimal varPct, BigDecimal rendimiento) {
		this.id = id;
		this.hora = hora;
		this.ultimo = ultimo;
		this.ppp = ppp;
		this.anterior = anterior;
		this.maximo = maximo;
		this.horaMaximo = horaMaximo;
		this.minimo = minimo;
		this.horaMinimo = horaMinimo;
		this.volumen = volumen;
		this.importe = importe;
		this.operaciones = operaciones;
		this.puntos = puntos;
		this.porcentaje = porcentaje;
		this.split = split;
		this.varPctPrecio = varPctPrecio;
		this.varPctMaximo = varPctMaximo;
		this.varPctMinimo = varPctMinimo;
		this.varPct = varPct;
		this.rendimiento = rendimiento;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "fecha", column = @Column(name = "fecha", nullable = false, length = 13)),
			@AttributeOverride(name = "emisora", column = @Column(name = "emisora", nullable = false, length = 25)),
			@AttributeOverride(name = "serie", column = @Column(name = "serie", nullable = false, length = 10)),
			@AttributeOverride(name = "idCarga", column = @Column(name = "id_carga", nullable = false)) })
	public SeriesOperadasIntraDiaId getId() {
		return this.id;
	}

	public void setId(SeriesOperadasIntraDiaId id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora", nullable = false, length = 15)
	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	@Column(name = "ultimo", nullable = false, precision = 16)
	public BigDecimal getUltimo() {
		return this.ultimo;
	}

	public void setUltimo(BigDecimal ultimo) {
		this.ultimo = ultimo;
	}

	@Column(name = "ppp", nullable = false, precision = 16)
	public BigDecimal getPpp() {
		return this.ppp;
	}

	public void setPpp(BigDecimal ppp) {
		this.ppp = ppp;
	}

	@Column(name = "anterior", nullable = false, precision = 16)
	public BigDecimal getAnterior() {
		return this.anterior;
	}

	public void setAnterior(BigDecimal anterior) {
		this.anterior = anterior;
	}

	@Column(name = "maximo", nullable = false, precision = 16)
	public BigDecimal getMaximo() {
		return this.maximo;
	}

	public void setMaximo(BigDecimal maximo) {
		this.maximo = maximo;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_maximo", nullable = false, length = 15)
	public Date getHoraMaximo() {
		return this.horaMaximo;
	}

	public void setHoraMaximo(Date horaMaximo) {
		this.horaMaximo = horaMaximo;
	}

	@Column(name = "minimo", nullable = false, precision = 16)
	public BigDecimal getMinimo() {
		return this.minimo;
	}

	public void setMinimo(BigDecimal minimo) {
		this.minimo = minimo;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_minimo", nullable = false, length = 15)
	public Date getHoraMinimo() {
		return this.horaMinimo;
	}

	public void setHoraMinimo(Date horaMinimo) {
		this.horaMinimo = horaMinimo;
	}

	@Column(name = "volumen", nullable = false, precision = 12, scale = 0)
	public long getVolumen() {
		return this.volumen;
	}

	public void setVolumen(long volumen) {
		this.volumen = volumen;
	}

	@Column(name = "importe", nullable = false, precision = 16)
	public BigDecimal getImporte() {
		return this.importe;
	}

	public void setImporte(BigDecimal importe) {
		this.importe = importe;
	}

	@Column(name = "operaciones", nullable = false, precision = 6, scale = 0)
	public int getOperaciones() {
		return this.operaciones;
	}

	public void setOperaciones(int operaciones) {
		this.operaciones = operaciones;
	}

	@Column(name = "puntos", nullable = false, precision = 8)
	public BigDecimal getPuntos() {
		return this.puntos;
	}

	public void setPuntos(BigDecimal puntos) {
		this.puntos = puntos;
	}

	@Column(name = "porcentaje", nullable = false, precision = 4)
	public BigDecimal getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(BigDecimal porcentaje) {
		this.porcentaje = porcentaje;
	}

	@Column(name = "split", nullable = false)
	public Integer getSplit() {
		return this.split;
	}

	public void setSplit(Integer split) {
		this.split = split;
	}

	@Column(name = "var_pct_precio", precision = 6, scale = 4)
	public BigDecimal getVarPctPrecio() {
		return this.varPctPrecio;
	}

	public void setVarPctPrecio(BigDecimal varPctPrecio) {
		this.varPctPrecio = varPctPrecio;
	}

	@Column(name = "var_pct_maximo", precision = 6, scale = 4)
	public BigDecimal getVarPctMaximo() {
		return this.varPctMaximo;
	}

	public void setVarPctMaximo(BigDecimal varPctMaximo) {
		this.varPctMaximo = varPctMaximo;
	}

	@Column(name = "var_pct_minimo", precision = 6, scale = 4)
	public BigDecimal getVarPctMinimo() {
		return this.varPctMinimo;
	}

	public void setVarPctMinimo(BigDecimal varPctMinimo) {
		this.varPctMinimo = varPctMinimo;
	}

	@Column(name = "var_pct", precision = 6, scale = 4)
	public BigDecimal getVarPct() {
		return this.varPct;
	}

	public void setVarPct(BigDecimal varPct) {
		this.varPct = varPct;
	}

	@Column(name = "rendimiento", precision = 6, scale = 4)
	public BigDecimal getRendimiento() {
		return this.rendimiento;
	}

	public void setRendimiento(BigDecimal rendimiento) {
		this.rendimiento = rendimiento;
	}

}
