package mx.com.analisispreciosmercado.conf;

// Generated 10/12/2008 06:03:50 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SeriesOperadasBk generated by hbm2java
 */
@Entity
@Table(name = "series_operadas_bk", schema = "public")
public class SeriesOperadasBk implements java.io.Serializable {

	private SeriesOperadasBkId id;

	public SeriesOperadasBk() {
	}

	public SeriesOperadasBk(SeriesOperadasBkId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "fecha", column = @Column(name = "fecha", length = 13)),
			@AttributeOverride(name = "emisora", column = @Column(name = "emisora", length = 25)),
			@AttributeOverride(name = "serie", column = @Column(name = "serie", length = 10)),
			@AttributeOverride(name = "hora", column = @Column(name = "hora", length = 15)),
			@AttributeOverride(name = "ultimo", column = @Column(name = "ultimo", precision = 16)),
			@AttributeOverride(name = "ppp", column = @Column(name = "ppp", precision = 16)),
			@AttributeOverride(name = "anterior", column = @Column(name = "anterior", precision = 16)),
			@AttributeOverride(name = "maximo", column = @Column(name = "maximo", precision = 16)),
			@AttributeOverride(name = "minimo", column = @Column(name = "minimo", precision = 16)),
			@AttributeOverride(name = "volumen", column = @Column(name = "volumen", precision = 12, scale = 0)),
			@AttributeOverride(name = "importe", column = @Column(name = "importe", precision = 16)),
			@AttributeOverride(name = "operaciones", column = @Column(name = "operaciones", precision = 6, scale = 0)),
			@AttributeOverride(name = "puntos", column = @Column(name = "puntos", precision = 8)),
			@AttributeOverride(name = "porcentaje", column = @Column(name = "porcentaje", precision = 4)),
			@AttributeOverride(name = "diaHabil", column = @Column(name = "dia_habil", length = 1)),
			@AttributeOverride(name = "split", column = @Column(name = "split")),
			@AttributeOverride(name = "varPctPrecio", column = @Column(name = "var_pct_precio", precision = 6, scale = 4)),
			@AttributeOverride(name = "varPctMaximo", column = @Column(name = "var_pct_maximo", precision = 6, scale = 4)),
			@AttributeOverride(name = "varPctMinimo", column = @Column(name = "var_pct_minimo", precision = 6, scale = 4)),
			@AttributeOverride(name = "varPct", column = @Column(name = "var_pct", precision = 6, scale = 4)),
			@AttributeOverride(name = "rendimiento", column = @Column(name = "rendimiento", precision = 4, scale = 3)),
			@AttributeOverride(name = "indBursatilidad", column = @Column(name = "ind_bursatilidad", precision = 9, scale = 6)),
			@AttributeOverride(name = "tipoIndBursatilidad", column = @Column(name = "tipo_ind_bursatilidad", length = 1)),
			@AttributeOverride(name = "cveTipoCarga", column = @Column(name = "cve_tipo_carga", length = 1)) })
	public SeriesOperadasBkId getId() {
		return this.id;
	}

	public void setId(SeriesOperadasBkId id) {
		this.id = id;
	}

}
