package mx.com.analisispreciosmercado.conf;

// Generated 10/12/2008 06:03:50 PM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SeriesOperadasBkId generated by hbm2java
 */
@Embeddable
public class SeriesOperadasBkId implements java.io.Serializable {

	private Date fecha;
	private String emisora;
	private String serie;
	private Date hora;
	private BigDecimal ultimo;
	private BigDecimal ppp;
	private BigDecimal anterior;
	private BigDecimal maximo;
	private BigDecimal minimo;
	private Long volumen;
	private BigDecimal importe;
	private Integer operaciones;
	private BigDecimal puntos;
	private BigDecimal porcentaje;
	private Character diaHabil;
	private Integer split;
	private BigDecimal varPctPrecio;
	private BigDecimal varPctMaximo;
	private BigDecimal varPctMinimo;
	private BigDecimal varPct;
	private BigDecimal rendimiento;
	private BigDecimal indBursatilidad;
	private Character tipoIndBursatilidad;
	private Character cveTipoCarga;

	public SeriesOperadasBkId() {
	}

	public SeriesOperadasBkId(Date fecha, String emisora, String serie,
			Date hora, BigDecimal ultimo, BigDecimal ppp, BigDecimal anterior,
			BigDecimal maximo, BigDecimal minimo, Long volumen,
			BigDecimal importe, Integer operaciones, BigDecimal puntos,
			BigDecimal porcentaje, Character diaHabil, Integer split,
			BigDecimal varPctPrecio, BigDecimal varPctMaximo,
			BigDecimal varPctMinimo, BigDecimal varPct, BigDecimal rendimiento,
			BigDecimal indBursatilidad, Character tipoIndBursatilidad,
			Character cveTipoCarga) {
		this.fecha = fecha;
		this.emisora = emisora;
		this.serie = serie;
		this.hora = hora;
		this.ultimo = ultimo;
		this.ppp = ppp;
		this.anterior = anterior;
		this.maximo = maximo;
		this.minimo = minimo;
		this.volumen = volumen;
		this.importe = importe;
		this.operaciones = operaciones;
		this.puntos = puntos;
		this.porcentaje = porcentaje;
		this.diaHabil = diaHabil;
		this.split = split;
		this.varPctPrecio = varPctPrecio;
		this.varPctMaximo = varPctMaximo;
		this.varPctMinimo = varPctMinimo;
		this.varPct = varPct;
		this.rendimiento = rendimiento;
		this.indBursatilidad = indBursatilidad;
		this.tipoIndBursatilidad = tipoIndBursatilidad;
		this.cveTipoCarga = cveTipoCarga;
	}

	@Column(name = "fecha", length = 13)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "emisora", length = 25)
	public String getEmisora() {
		return this.emisora;
	}

	public void setEmisora(String emisora) {
		this.emisora = emisora;
	}

	@Column(name = "serie", length = 10)
	public String getSerie() {
		return this.serie;
	}

	public void setSerie(String serie) {
		this.serie = serie;
	}

	@Column(name = "hora", length = 15)
	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	@Column(name = "ultimo", precision = 16)
	public BigDecimal getUltimo() {
		return this.ultimo;
	}

	public void setUltimo(BigDecimal ultimo) {
		this.ultimo = ultimo;
	}

	@Column(name = "ppp", precision = 16)
	public BigDecimal getPpp() {
		return this.ppp;
	}

	public void setPpp(BigDecimal ppp) {
		this.ppp = ppp;
	}

	@Column(name = "anterior", precision = 16)
	public BigDecimal getAnterior() {
		return this.anterior;
	}

	public void setAnterior(BigDecimal anterior) {
		this.anterior = anterior;
	}

	@Column(name = "maximo", precision = 16)
	public BigDecimal getMaximo() {
		return this.maximo;
	}

	public void setMaximo(BigDecimal maximo) {
		this.maximo = maximo;
	}

	@Column(name = "minimo", precision = 16)
	public BigDecimal getMinimo() {
		return this.minimo;
	}

	public void setMinimo(BigDecimal minimo) {
		this.minimo = minimo;
	}

	@Column(name = "volumen", precision = 12, scale = 0)
	public Long getVolumen() {
		return this.volumen;
	}

	public void setVolumen(Long volumen) {
		this.volumen = volumen;
	}

	@Column(name = "importe", precision = 16)
	public BigDecimal getImporte() {
		return this.importe;
	}

	public void setImporte(BigDecimal importe) {
		this.importe = importe;
	}

	@Column(name = "operaciones", precision = 6, scale = 0)
	public Integer getOperaciones() {
		return this.operaciones;
	}

	public void setOperaciones(Integer operaciones) {
		this.operaciones = operaciones;
	}

	@Column(name = "puntos", precision = 8)
	public BigDecimal getPuntos() {
		return this.puntos;
	}

	public void setPuntos(BigDecimal puntos) {
		this.puntos = puntos;
	}

	@Column(name = "porcentaje", precision = 4)
	public BigDecimal getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(BigDecimal porcentaje) {
		this.porcentaje = porcentaje;
	}

	@Column(name = "dia_habil", length = 1)
	public Character getDiaHabil() {
		return this.diaHabil;
	}

	public void setDiaHabil(Character diaHabil) {
		this.diaHabil = diaHabil;
	}

	@Column(name = "split")
	public Integer getSplit() {
		return this.split;
	}

	public void setSplit(Integer split) {
		this.split = split;
	}

	@Column(name = "var_pct_precio", precision = 6, scale = 4)
	public BigDecimal getVarPctPrecio() {
		return this.varPctPrecio;
	}

	public void setVarPctPrecio(BigDecimal varPctPrecio) {
		this.varPctPrecio = varPctPrecio;
	}

	@Column(name = "var_pct_maximo", precision = 6, scale = 4)
	public BigDecimal getVarPctMaximo() {
		return this.varPctMaximo;
	}

	public void setVarPctMaximo(BigDecimal varPctMaximo) {
		this.varPctMaximo = varPctMaximo;
	}

	@Column(name = "var_pct_minimo", precision = 6, scale = 4)
	public BigDecimal getVarPctMinimo() {
		return this.varPctMinimo;
	}

	public void setVarPctMinimo(BigDecimal varPctMinimo) {
		this.varPctMinimo = varPctMinimo;
	}

	@Column(name = "var_pct", precision = 6, scale = 4)
	public BigDecimal getVarPct() {
		return this.varPct;
	}

	public void setVarPct(BigDecimal varPct) {
		this.varPct = varPct;
	}

	@Column(name = "rendimiento", precision = 4, scale = 3)
	public BigDecimal getRendimiento() {
		return this.rendimiento;
	}

	public void setRendimiento(BigDecimal rendimiento) {
		this.rendimiento = rendimiento;
	}

	@Column(name = "ind_bursatilidad", precision = 9, scale = 6)
	public BigDecimal getIndBursatilidad() {
		return this.indBursatilidad;
	}

	public void setIndBursatilidad(BigDecimal indBursatilidad) {
		this.indBursatilidad = indBursatilidad;
	}

	@Column(name = "tipo_ind_bursatilidad", length = 1)
	public Character getTipoIndBursatilidad() {
		return this.tipoIndBursatilidad;
	}

	public void setTipoIndBursatilidad(Character tipoIndBursatilidad) {
		this.tipoIndBursatilidad = tipoIndBursatilidad;
	}

	@Column(name = "cve_tipo_carga", length = 1)
	public Character getCveTipoCarga() {
		return this.cveTipoCarga;
	}

	public void setCveTipoCarga(Character cveTipoCarga) {
		this.cveTipoCarga = cveTipoCarga;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SeriesOperadasBkId))
			return false;
		SeriesOperadasBkId castOther = (SeriesOperadasBkId) other;

		return ((this.getFecha() == castOther.getFecha()) || (this.getFecha() != null
				&& castOther.getFecha() != null && this.getFecha().equals(
				castOther.getFecha())))
				&& ((this.getEmisora() == castOther.getEmisora()) || (this
						.getEmisora() != null
						&& castOther.getEmisora() != null && this.getEmisora()
						.equals(castOther.getEmisora())))
				&& ((this.getSerie() == castOther.getSerie()) || (this
						.getSerie() != null
						&& castOther.getSerie() != null && this.getSerie()
						.equals(castOther.getSerie())))
				&& ((this.getHora() == castOther.getHora()) || (this.getHora() != null
						&& castOther.getHora() != null && this.getHora()
						.equals(castOther.getHora())))
				&& ((this.getUltimo() == castOther.getUltimo()) || (this
						.getUltimo() != null
						&& castOther.getUltimo() != null && this.getUltimo()
						.equals(castOther.getUltimo())))
				&& ((this.getPpp() == castOther.getPpp()) || (this.getPpp() != null
						&& castOther.getPpp() != null && this.getPpp().equals(
						castOther.getPpp())))
				&& ((this.getAnterior() == castOther.getAnterior()) || (this
						.getAnterior() != null
						&& castOther.getAnterior() != null && this
						.getAnterior().equals(castOther.getAnterior())))
				&& ((this.getMaximo() == castOther.getMaximo()) || (this
						.getMaximo() != null
						&& castOther.getMaximo() != null && this.getMaximo()
						.equals(castOther.getMaximo())))
				&& ((this.getMinimo() == castOther.getMinimo()) || (this
						.getMinimo() != null
						&& castOther.getMinimo() != null && this.getMinimo()
						.equals(castOther.getMinimo())))
				&& ((this.getVolumen() == castOther.getVolumen()) || (this
						.getVolumen() != null
						&& castOther.getVolumen() != null && this.getVolumen()
						.equals(castOther.getVolumen())))
				&& ((this.getImporte() == castOther.getImporte()) || (this
						.getImporte() != null
						&& castOther.getImporte() != null && this.getImporte()
						.equals(castOther.getImporte())))
				&& ((this.getOperaciones() == castOther.getOperaciones()) || (this
						.getOperaciones() != null
						&& castOther.getOperaciones() != null && this
						.getOperaciones().equals(castOther.getOperaciones())))
				&& ((this.getPuntos() == castOther.getPuntos()) || (this
						.getPuntos() != null
						&& castOther.getPuntos() != null && this.getPuntos()
						.equals(castOther.getPuntos())))
				&& ((this.getPorcentaje() == castOther.getPorcentaje()) || (this
						.getPorcentaje() != null
						&& castOther.getPorcentaje() != null && this
						.getPorcentaje().equals(castOther.getPorcentaje())))
				&& ((this.getDiaHabil() == castOther.getDiaHabil()) || (this
						.getDiaHabil() != null
						&& castOther.getDiaHabil() != null && this
						.getDiaHabil().equals(castOther.getDiaHabil())))
				&& ((this.getSplit() == castOther.getSplit()) || (this
						.getSplit() != null
						&& castOther.getSplit() != null && this.getSplit()
						.equals(castOther.getSplit())))
				&& ((this.getVarPctPrecio() == castOther.getVarPctPrecio()) || (this
						.getVarPctPrecio() != null
						&& castOther.getVarPctPrecio() != null && this
						.getVarPctPrecio().equals(castOther.getVarPctPrecio())))
				&& ((this.getVarPctMaximo() == castOther.getVarPctMaximo()) || (this
						.getVarPctMaximo() != null
						&& castOther.getVarPctMaximo() != null && this
						.getVarPctMaximo().equals(castOther.getVarPctMaximo())))
				&& ((this.getVarPctMinimo() == castOther.getVarPctMinimo()) || (this
						.getVarPctMinimo() != null
						&& castOther.getVarPctMinimo() != null && this
						.getVarPctMinimo().equals(castOther.getVarPctMinimo())))
				&& ((this.getVarPct() == castOther.getVarPct()) || (this
						.getVarPct() != null
						&& castOther.getVarPct() != null && this.getVarPct()
						.equals(castOther.getVarPct())))
				&& ((this.getRendimiento() == castOther.getRendimiento()) || (this
						.getRendimiento() != null
						&& castOther.getRendimiento() != null && this
						.getRendimiento().equals(castOther.getRendimiento())))
				&& ((this.getIndBursatilidad() == castOther
						.getIndBursatilidad()) || (this.getIndBursatilidad() != null
						&& castOther.getIndBursatilidad() != null && this
						.getIndBursatilidad().equals(
								castOther.getIndBursatilidad())))
				&& ((this.getTipoIndBursatilidad() == castOther
						.getTipoIndBursatilidad()) || (this
						.getTipoIndBursatilidad() != null
						&& castOther.getTipoIndBursatilidad() != null && this
						.getTipoIndBursatilidad().equals(
								castOther.getTipoIndBursatilidad())))
				&& ((this.getCveTipoCarga() == castOther.getCveTipoCarga()) || (this
						.getCveTipoCarga() != null
						&& castOther.getCveTipoCarga() != null && this
						.getCveTipoCarga().equals(castOther.getCveTipoCarga())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getFecha() == null ? 0 : this.getFecha().hashCode());
		result = 37 * result
				+ (getEmisora() == null ? 0 : this.getEmisora().hashCode());
		result = 37 * result
				+ (getSerie() == null ? 0 : this.getSerie().hashCode());
		result = 37 * result
				+ (getHora() == null ? 0 : this.getHora().hashCode());
		result = 37 * result
				+ (getUltimo() == null ? 0 : this.getUltimo().hashCode());
		result = 37 * result
				+ (getPpp() == null ? 0 : this.getPpp().hashCode());
		result = 37 * result
				+ (getAnterior() == null ? 0 : this.getAnterior().hashCode());
		result = 37 * result
				+ (getMaximo() == null ? 0 : this.getMaximo().hashCode());
		result = 37 * result
				+ (getMinimo() == null ? 0 : this.getMinimo().hashCode());
		result = 37 * result
				+ (getVolumen() == null ? 0 : this.getVolumen().hashCode());
		result = 37 * result
				+ (getImporte() == null ? 0 : this.getImporte().hashCode());
		result = 37
				* result
				+ (getOperaciones() == null ? 0 : this.getOperaciones()
						.hashCode());
		result = 37 * result
				+ (getPuntos() == null ? 0 : this.getPuntos().hashCode());
		result = 37
				* result
				+ (getPorcentaje() == null ? 0 : this.getPorcentaje()
						.hashCode());
		result = 37 * result
				+ (getDiaHabil() == null ? 0 : this.getDiaHabil().hashCode());
		result = 37 * result
				+ (getSplit() == null ? 0 : this.getSplit().hashCode());
		result = 37
				* result
				+ (getVarPctPrecio() == null ? 0 : this.getVarPctPrecio()
						.hashCode());
		result = 37
				* result
				+ (getVarPctMaximo() == null ? 0 : this.getVarPctMaximo()
						.hashCode());
		result = 37
				* result
				+ (getVarPctMinimo() == null ? 0 : this.getVarPctMinimo()
						.hashCode());
		result = 37 * result
				+ (getVarPct() == null ? 0 : this.getVarPct().hashCode());
		result = 37
				* result
				+ (getRendimiento() == null ? 0 : this.getRendimiento()
						.hashCode());
		result = 37
				* result
				+ (getIndBursatilidad() == null ? 0 : this.getIndBursatilidad()
						.hashCode());
		result = 37
				* result
				+ (getTipoIndBursatilidad() == null ? 0 : this
						.getTipoIndBursatilidad().hashCode());
		result = 37
				* result
				+ (getCveTipoCarga() == null ? 0 : this.getCveTipoCarga()
						.hashCode());
		return result;
	}

}
