/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OtroFrame.java
 *
 * Created on 21-abr-2009, 22:36:42
 */
package caafe.cliente;

import caafes.def.Clientes;
import clientes.servicio.ServicioCliente;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.JOptionPane;
import otro.MiJDialog;
import otro.Pass;

/**
 *
 * @author Edgar
 */
public class Cliente extends MiJDialog {

    private Clientes nuevo = null;
    private Pass frmPass = null;
    private Boolean bEstado = null;
    private int iEstatus;
    public final static int NUEVO = 100;
    public final static int CONSULTAR = 101;
    public final static int EDITAR = 102;

    /** Creates new form OtroFrame */
    public Cliente() {
        initComponents();
    }

    public void actualizaForm(int iEstatus, BigDecimal iDCliente) {
        this.iEstatus = iEstatus;

        if (iEstatus == CONSULTAR) {
            jtxArchivo.setEnabled(false);
            jtxNombre.setEnabled(false);
            jtxApellido.setEnabled(false);
            jtxRFC.setEnabled(false);
            jtxTelefono.setEnabled(false);
            jtxCalleNumero.setEnabled(false);
            jtxCiudad.setEnabled(false);
            jtxCodigoPostal.setEnabled(false);
            jtxColonia.setEnabled(false);
            jtxDelegacion.setEnabled(false);
            ServicioCliente srvCliente = new ServicioCliente();

            nuevo = srvCliente.obtieneCliente(iDCliente, null);

            jtxArchivo.setText(nuevo.getNumeroArchivo());
            jtxNombre.setText(nuevo.getNombre());
            jtxApellido.setText(nuevo.getApellidos());
            jtxRFC.setText(nuevo.getRfc());
            jtxTelefono.setText(String.valueOf(nuevo.getTelefono()));
            jtxCalleNumero.setText(nuevo.getCalleNumero());
            jtxCiudad.setText(nuevo.getCiudad());
            jtxCodigoPostal.setText(String.valueOf(nuevo.getCodigoPostal()));
            jtxColonia.setText(nuevo.getColonia());
            jtxDelegacion.setText(nuevo.getDelegacionMunicipio());


            jbAceptar.setText("Editar");
        }


        if (iEstatus == NUEVO) {
            jtxArchivo.setEnabled(true);
            jtxNombre.setEnabled(true);
            jtxApellido.setEnabled(true);
            jtxRFC.setEnabled(true);
            jtxTelefono.setEnabled(true);
            jtxCalleNumero.setEnabled(true);
            jtxCiudad.setEnabled(true);
            jtxCodigoPostal.setEnabled(true);
            jtxColonia.setEnabled(true);
            jtxDelegacion.setEnabled(true);
            jbAceptar.setText("Agregar");
            limpiaForma();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jbAceptar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jtxNombre = new javax.swing.JTextField();
        jtxApellido = new javax.swing.JTextField();
        jtxRFC = new javax.swing.JTextField();
        jtxCalleNumero = new javax.swing.JTextField();
        jtxColonia = new javax.swing.JTextField();
        jtxDelegacion = new javax.swing.JTextField();
        jtxCiudad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtxTelefono = new javax.swing.JTextField();
        jtxCodigoPostal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtxArchivo = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setTitle("Agregar Cliente");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellidos");

        jLabel3.setText("RFC");

        jLabel4.setText("Calle y Numero");

        jLabel5.setText("Colonia");

        jLabel6.setText("Codigo Postal");

        jLabel7.setText("Delegación/Municipio");

        jLabel8.setText("Ciudad");

        jbAceptar.setText("Agregar");
        jbAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAceptarActionPerformed(evt);
            }
        });

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jtxNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxNombreKeyPressed(evt);
            }
        });

        jtxApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxApellidoKeyPressed(evt);
            }
        });

        jtxRFC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxRFCKeyPressed(evt);
            }
        });

        jtxColonia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxColoniaKeyPressed(evt);
            }
        });

        jtxDelegacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxDelegacionKeyPressed(evt);
            }
        });

        jtxCiudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxCiudadKeyPressed(evt);
            }
        });

        jLabel9.setText("Telefono");

        jtxTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxTelefonoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxTelefonoKeyReleased(evt);
            }
        });

        jtxCodigoPostal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxCodigoPostalKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxCodigoPostalKeyReleased(evt);
            }
        });

        jLabel10.setText("Numero en Archivo");

        jtxArchivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxArchivoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxArchivoKeyReleased(evt);
            }
        });

        jMenu1.setText("Archivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Agregar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Acerca");

        jMenuItem2.setText("Ayuda");
        jMenu2.add(jMenuItem2);

        jMenuItem4.setText("Acerca...");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(jtxApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(jtxRFC, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(jtxCalleNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtxCodigoPostal, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                .addGap(110, 110, 110))
                            .addComponent(jtxDelegacion, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(jtxColonia, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jbAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                .addGap(30, 30, 30)
                                .addComponent(jbSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                            .addComponent(jtxTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(jtxNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtxArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtxArchivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1))
                    .addComponent(jtxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2))
                    .addComponent(jtxApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3))
                    .addComponent(jtxRFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4))
                    .addComponent(jtxCalleNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5))
                    .addComponent(jtxColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6))
                    .addComponent(jtxCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7))
                    .addComponent(jtxDelegacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel9))
                    .addComponent(jtxTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtxCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAceptarActionPerformed
        switch (iEstatus) {
            case NUEVO:
                estado();
                desborde();
                if (bEstado == true) {
                    insertaCliente();

                }
                break;
            case EDITAR:
                modificaCliente();
                JOptionPane.showMessageDialog(this, "Datos Guardados con éxito", "", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                break;
            case CONSULTAR:
                if (frmPass == null) {
                    frmPass = new Pass(this, 1);
                }
                frmPass.limpiaFrame();
                frmPass.setVisible(true);
                frmPass.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                frmPass.setAlwaysOnTop(true);
                frmPass.setLocationRelativeTo(this);
                break;
        }
}//GEN-LAST:event_jbAceptarActionPerformed

    @Override
    public void cbPasswprd() {
        jtxArchivo.setEnabled(true);
        jtxNombre.setEnabled(true);
        jtxApellido.setEnabled(true);
        jtxRFC.setEnabled(true);
        jtxTelefono.setEnabled(true);
        jtxCalleNumero.setEnabled(true);
        jtxCiudad.setEnabled(true);
        jtxCodigoPostal.setEnabled(true);
        jtxColonia.setEnabled(true);
        jtxDelegacion.setEnabled(true);
        iEstatus = EDITAR;
        jbAceptar.setText("Guardar");
    }

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        this.dispose();
}//GEN-LAST:event_jbSalirActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        estado();
        desborde();
        if (bEstado == true) {
            insertaCliente();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void jtxArchivoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxArchivoKeyPressed
       String cSubstring = jtxArchivo.getText();
        if (jtxArchivo.getText().length() >= 5&&ignoraKey(evt)) {
            JOptionPane.showMessageDialog(this, "El campo Archivo solo acepta 5 caracteres\n", "Demasiados caracteres", JOptionPane.ERROR_MESSAGE);
            jtxArchivo.setText(cSubstring.substring(0, 5));
        }
    }//GEN-LAST:event_jtxArchivoKeyPressed

    private void jtxNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxNombreKeyPressed
    String cSubstring = jtxNombre.getText();
        if (jtxNombre.getText().length() >= 20&&ignoraKey(evt)) {
            JOptionPane.showMessageDialog(this, "El campo Nombre solo acepta 20 caracteres\n", "Demasiados caracteres", JOptionPane.ERROR_MESSAGE);
            jtxNombre.setText(cSubstring.substring(0, 20));
        } 
    }//GEN-LAST:event_jtxNombreKeyPressed

    private void jtxApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxApellidoKeyPressed
String cSubstring = jtxApellido.getText();
        if (jtxApellido.getText().length() >= 50&&ignoraKey(evt)) {
            JOptionPane.showMessageDialog(this, "El campo Apellidos solo acepta 50 caracteres\n", "Demasiados caracteres", JOptionPane.ERROR_MESSAGE);
            jtxApellido.setText(cSubstring.substring(0, 50));
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jtxApellidoKeyPressed

    private void jtxRFCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxRFCKeyPressed
String cSubstring = jtxRFC.getText();
        if (jtxRFC.getText().length() >= 13&&ignoraKey(evt)) {
            JOptionPane.showMessageDialog(this, "El campo RFC solo acepta 13 caracteres\n", "Demasiados caracteres", JOptionPane.ERROR_MESSAGE);
            jtxRFC.setText(cSubstring.substring(0, 13));
        }         // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jtxRFCKeyPressed

    private void jtxColoniaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxColoniaKeyPressed
String cSubstring = jtxColonia.getText();
        if (jtxColonia.getText().length() >= 20&&ignoraKey(evt)) {
            JOptionPane.showMessageDialog(this, "El campo Colonia solo acepta 20 caracteres\n", "Demasiados caracteres", JOptionPane.ERROR_MESSAGE);
            jtxColonia.setText(cSubstring.substring(0, 20));
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jtxColoniaKeyPressed

    private void jtxCodigoPostalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxCodigoPostalKeyPressed
String cSubstring = jtxCodigoPostal.getText();


        if (jtxCodigoPostal.getText().length() >= 7&&ignoraKey(evt)) {
            JOptionPane.showMessageDialog(this, "El campo Codigo Postal solo acepta 7 caracteres\n", "Demasiados caracteres", JOptionPane.ERROR_MESSAGE);
            jtxCodigoPostal.setText(cSubstring.substring(0, 7));
            }

         
    }//GEN-LAST:event_jtxCodigoPostalKeyPressed

    private void jtxCodigoPostalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxCodigoPostalKeyReleased
  BigDecimal bdCantidad = null;
        if (!jtxCodigoPostal.getText().equals("")) {
            try {
                bdCantidad = new BigDecimal(jtxCodigoPostal.getText());

            } catch (Exception exception) {
                JOptionPane.showMessageDialog(this, "El Codigo Postal debe de ser numerico", "Error", JOptionPane.ERROR_MESSAGE);
                jtxCodigoPostal.setText("");
            }
        }             // TODO add your handling code here:
    }//GEN-LAST:event_jtxCodigoPostalKeyReleased

    private void jtxDelegacionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxDelegacionKeyPressed
String cSubstring = jtxDelegacion.getText();
       if (jtxDelegacion.getText().length() >= 20&&ignoraKey(evt)) {
            JOptionPane.showMessageDialog(this, "El campo Delegacion O municipio solo acepta 20 caracteres\n", "Demasiados caracteres", JOptionPane.ERROR_MESSAGE);
            jtxDelegacion.setText(cSubstring.substring(0, 20));
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jtxDelegacionKeyPressed

    private void jtxTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxTelefonoKeyPressed
      String cSubstring = jtxTelefono.getText();
        if (jtxTelefono.getText().length() >= 15&&ignoraKey(evt)) {
            JOptionPane.showMessageDialog(this, "El campo Telefono solo acepta 15 caracteres\n", "Demasiados caracteres", JOptionPane.ERROR_MESSAGE);
            jtxTelefono.setText(cSubstring.substring(0, 15));
        }// TODO add your handling code here:
    }//GEN-LAST:event_jtxTelefonoKeyPressed

    private void jtxCiudadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxCiudadKeyPressed
        String cSubstring = jtxCiudad.getText();
        if (jtxCiudad.getText().length() >= 20&&ignoraKey(evt)) {
            JOptionPane.showMessageDialog(this, "El campo Ciudad solo acepta 20 caracteres\n", "Demasiados caracteres", JOptionPane.ERROR_MESSAGE);
            jtxCiudad.setText(cSubstring.substring(0, 20));
        }// TODO add your handling code here:
    }//GEN-LAST:event_jtxCiudadKeyPressed

    private void jtxTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxTelefonoKeyReleased
 BigDecimal bdCantidad = null;

        if (!jtxTelefono.getText().equals("")) {
            try {
                bdCantidad = new BigDecimal(jtxTelefono.getText());

            } catch (Exception exception) {
                JOptionPane.showMessageDialog(this, "El Telefono debe de ser numerico", "Error", JOptionPane.ERROR_MESSAGE);
                jtxTelefono.setText("");
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jtxTelefonoKeyReleased

    private void jtxArchivoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxArchivoKeyReleased
  BigDecimal bdCantidad = null;
        if (!jtxArchivo.getText().equals("")) {
            try {
                bdCantidad = new BigDecimal(jtxArchivo.getText());

            } catch (Exception exception) {
                JOptionPane.showMessageDialog(this, "El Numero de Archivo debe de ser numerico", "Error", JOptionPane.ERROR_MESSAGE);
                jtxArchivo.setText("");
            }
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jtxArchivoKeyReleased
    
    
    public boolean  ignoraKey(java.awt.event.KeyEvent evt){
        if(evt.getKeyCode()==10||evt.getKeyCode()==18||evt.getKeyCode()==17||evt.getKeyCode()==8||evt.getKeyCode()==127||evt.getKeyCode()==155||evt.getKeyCode()==16||evt.getKeyCode()==20||evt.getKeyCode()==33||evt.getKeyCode()==34||evt.getKeyCode()==35||evt.getKeyCode()==36||evt.getKeyCode()==37||evt.getKeyCode()==38||evt.getKeyCode()==39||evt.getKeyCode()==40){
            return false;
        }else{
            return true;
        }
    }

    public void insertaCliente() {
        System.out.println("inserta cliente:");
        nuevo = new Clientes();
        ServicioCliente srvCliente = new ServicioCliente();



        String strClientes;
        List<Clientes> lista;

        if (bEstado == true) {
            strClientes = jtxRFC.getText();
            lista = srvCliente.obtieneClientes(strClientes);
            if (lista != null) {
                if (lista.isEmpty()) {
                    insertaClienteReviso();
                } else {
                    JOptionPane.showMessageDialog(this, "El RFC ya exciste", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                insertaClienteReviso();
            }
        }

        srvCliente.insertaCliente(nuevo);

        limpiaForma();

    }

    public void insertaClienteReviso() {
        nuevo.setNumeroArchivo(jtxArchivo.getText());
        nuevo.setNombre(jtxNombre.getText().toUpperCase());
        nuevo.setApellidos(jtxApellido.getText().toUpperCase());
        nuevo.setRfc(jtxRFC.getText().toUpperCase());
        nuevo.setCalleNumero(jtxCalleNumero.getText().toUpperCase());
        nuevo.setColonia(jtxColonia.getText().toUpperCase());
        nuevo.setCodigoPostal(jtxCodigoPostal.getText());
        nuevo.setDelegacionMunicipio(jtxDelegacion.getText().toUpperCase());
        nuevo.setTelefono(jtxTelefono.getText());
        nuevo.setCiudad(jtxCiudad.getText().toUpperCase());
        nuevo.setExportado(Character.valueOf('N'));
    }

    public void modificaCliente() {
        System.out.println("inserta cliente:");

        nuevo.setNumeroArchivo(jtxArchivo.getText());
        nuevo.setNombre(jtxNombre.getText().toUpperCase());
        nuevo.setApellidos(jtxApellido.getText().toUpperCase());
        nuevo.setRfc(jtxRFC.getText());
        nuevo.setCalleNumero(jtxCalleNumero.getText().toUpperCase());
        nuevo.setColonia(jtxColonia.getText().toUpperCase());
        nuevo.setCodigoPostal(jtxCodigoPostal.getText());
        nuevo.setDelegacionMunicipio(jtxDelegacion.getText().toUpperCase());
        nuevo.setTelefono(jtxTelefono.getText());
        nuevo.setCiudad(jtxCiudad.getText());

        ServicioCliente servicioCliente = new ServicioCliente();
        servicioCliente.modificaCliente(nuevo);

        limpiaForma();
    }

    private void limpiaForma() {
        jtxArchivo.setText("");
        jtxNombre.setText("");
        jtxApellido.setText("");
        jtxRFC.setText("");
        jtxTelefono.setText("");
        jtxCalleNumero.setText("");
        jtxCiudad.setText("");
        jtxCodigoPostal.setText("");
        jtxColonia.setText("");
        jtxDelegacion.setText("");
    }

    public void desborde() {
        StringBuilder sbError = new StringBuilder("");
        boolean bEntra = false;

        if (jtxArchivo.getText().length() > 20) {
            sbError.append("El campo Archivo solo acepta 20 caracteres\n");
            bEntra = true;
        }
        if (jtxNombre.getText().length() > 20) {
            sbError.append("El campo Nombre solo acepta 20 caracteres\n");
            bEntra = true;
        }
        if (jtxApellido.getText().length() > 50) {
            sbError.append("El campo Apellido solo acepta 50 caracteres\n");
            bEntra = true;

        }
        if (jtxRFC.getText().length() > 13) {
            sbError.append("El campo RFC solo acepta 13 caracteres \n");
            bEntra = true;
        }
        if (jtxCalleNumero.getText().length() > 50) {
            sbError.append("El campo Calle y numero solo acepta 50 caracteres\n");
            bEntra = true;
        }
        if (jtxColonia.getText().length() > 20) {
            sbError.append("El campo Colonia solo acepta 20 caracteres\n");
            bEntra = true;
        }
        if (jtxCodigoPostal.getText().length() > 7) {
            sbError.append("El campo Codigo postal solo acepta 7 caracteres\n");
            bEntra = true;
        }
        if (jtxDelegacion.getText().length() > 20) {
            sbError.append("El campo Delegacion solo acepta 20 caracteres\n");
            bEntra = true;
        }
        if (jtxCiudad.getText().length() > 20) {
            sbError.append("El campo Ciudad solo acepta 20 caracteres\n");
            bEntra = true;
        }
        if (jtxTelefono.getText().length() > 15) {
            sbError.append("El campo Telefono solo acepta 15 caracteres\n");
            bEntra = true;
        }

        if (bEntra == true) {
            JOptionPane.showMessageDialog(this, "" + sbError, "Demasiados caracteres", JOptionPane.ERROR_MESSAGE);
            bEstado = false;
        }

    }

    public void estado() {
        String sNombre;
        String sApellido;
        String sRfc;
        String sCalle;
        String sColonia;
        String sCodigo;
        String sTel;
        String sCiudad;
        StringBuilder sbFaltantes = new StringBuilder("");
        boolean bFaltan = false;

        sNombre = jtxNombre.getText();
        sApellido = jtxApellido.getText();
        sRfc = jtxRFC.getText();
        sCalle = jtxCalleNumero.getText();
        sColonia = jtxColonia.getText();
        sCodigo = jtxCodigoPostal.getText();

        if (jtxTelefono.getText() != null) {
            sTel = jtxTelefono.getText();
        } else {
            sTel = "";
        }

        sCiudad = jtxCiudad.getText();

        if (sNombre.equals("")) {
            sbFaltantes.append("Nombre \n");
            bFaltan = true;
        }
        if (sApellido.equals("")) {
            sbFaltantes.append("Apellido\n");
            bFaltan = true;
        }
        if (sRfc.equals("")) {
            sbFaltantes.append("RFC\n");
            bFaltan = true;
        }
        if (sCalle.equals("")) {
            sbFaltantes.append("Calle\n");
            bFaltan = true;
        }
        if (sColonia.equals("")) {
            sbFaltantes.append("Colonia\n");
            bFaltan = true;
        }
        if (sCodigo.equals("")) {
            sbFaltantes.append("Codigo Postal\n");
            bFaltan = true;
        }
        if (sTel.equals("")) {
            sbFaltantes.append("Teléfono\n");
            bFaltan = true;
        }
        if (sCiudad.equals("")) {
            sbFaltantes.append("Ciudad\n");
            bFaltan = true;
        }
        if (bFaltan == true) {
            JOptionPane.showMessageDialog(this, "Los campos:\n" + sbFaltantes + "Son requeridos", "Campos faltantes", JOptionPane.ERROR_MESSAGE);
            bEstado = false;
        } else {

            bEstado = true;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JButton jbAceptar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JTextField jtxApellido;
    private javax.swing.JTextField jtxArchivo;
    private javax.swing.JTextField jtxCalleNumero;
    private javax.swing.JTextField jtxCiudad;
    private javax.swing.JTextField jtxCodigoPostal;
    private javax.swing.JTextField jtxColonia;
    private javax.swing.JTextField jtxDelegacion;
    private javax.swing.JTextField jtxNombre;
    private javax.swing.JTextField jtxRFC;
    private javax.swing.JTextField jtxTelefono;
    // End of variables declaration//GEN-END:variables
}
