/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Ficha.java
 *
 * Created on 15-jun-2009, 11:53:52
 */
package mx.com.controlesvisuales.vista;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Paint;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import mx.com.controlesvisuales.modelo.ModeloFicha;

/**
 *
 * @author sigfrido
 * @version 1.0
 *
 * Clase que sirve como la ficha que representa cada profesor
 */
public class Ficha extends javax.swing.JPanel {

    private int arcw = 20;
    private int arch = 20;
    private float anchoLinea = 4f;
    private Color colorPrimario = Color.GREEN;
    private Color colorSecundario = Color.GREEN;
    private Color colorContorno = Color.GREEN;
    private Color colorFuente = Color.BLUE;
    private boolean bBrilloso = false;
    private ModeloFicha modeloFicha;
    private int iPosX = 0;
    private int iPosY = 0;

    /** Creates new form Ficha */
    public Ficha() {
        super();
        setOpaque(false);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setToolTipText("Ejemplo");
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        System.out.println("formMouseClicked");
    }//GEN-LAST:event_formMouseClicked

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        System.out.println("formMouseEntered");
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        System.out.println("formMouseClicked");
    }//GEN-LAST:event_formMouseExited

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        System.out.println("formMousePressed");
        System.out.println("Repintamos el boton pero mas brillante");

        bBrilloso = true;
        this.repaint();
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        System.out.println("formMouseReleased");
        System.out.println("Repintamos el boton pero opaco");

        bBrilloso = false;
        this.repaint();
    }//GEN-LAST:event_formMouseReleased

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        System.out.println("formMouseDragged::"+evt);
        iPosX = evt.getX();
        iPosY = evt.getY();
        this.repaint();
    }//GEN-LAST:event_formMouseDragged

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        System.out.println("formMouseMoved");
    }//GEN-LAST:event_formMouseMoved

    @Override
    protected void paintComponent(Graphics g) {
        System.out.println("paintComponent");
        Graphics2D g2 = (Graphics2D) g;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                RenderingHints.VALUE_ANTIALIAS_ON);


        Paint oldPaint = g2.getPaint();
//        RoundRectangle2D.Float r2d = new RoundRectangle2D.Float(
//                0, 0, getWidth() - 1, getHeight() - 1, getArcw(), getArch());
//        g2.clip(r2d);

//        if (!bBrilloso) {
//            g2.setPaint(new GradientPaint(0.0f, 0.0f, getColorPrimario().darker(),
//                    0.0f, getHeight(), getColorSecundario().darker()));
//
//            g2.setPaint(new GradientPaint(0.0f, 0.0f, getColorContorno().darker(),
//                    0.0f, getHeight(), getColorContorno().darker()));
//        } else {
//            g2.setPaint(new GradientPaint(0.0f, 0.0f, getColorPrimario(),
//                    0.0f, getHeight(), getColorSecundario()));
//
//            g2.setPaint(new GradientPaint(0.0f, 0.0f, getColorContorno(),
//                    0.0f, getHeight(), getColorContorno()));
//        }
        //Relleno del panel
        g2.fillRect(iPosX, iPosY, getWidth(), getHeight());
        //Grosor de linea de contorno y dibujado del contorno
//        g2.setStroke(new BasicStroke(getAnchoLinea()));
//        g2.drawRoundRect(0, 0, getWidth() - 2, getHeight() - 2, getArcw(), getArch());

        //Pintamos el texto del mensaje del modelo
//        pintarTexto(g2);
        
        g2.setPaint(oldPaint);
        super.paintComponent(g);
    }

    private void pintarTexto(Graphics2D g2){
        String strMensaje = "17";
        int iY = (getHeight()/2)+3;
        int iX = (getWidth()/2)-(strMensaje.length()*3);

        if (!bBrilloso) {
            g2.setColor(getColorFuente().darker());
        } else {
            g2.setColor(getColorFuente());
        }
        g2.drawString(strMensaje, iX, iY);
    }

    public Color getColorFuente() {
        return colorFuente;
    }

    public void setColorFuente(Color colorFuente) {
        this.colorFuente = colorFuente;
    }

    public Color getColorContorno() {
        return colorContorno;
    }

    public float getAnchoLinea() {
        return anchoLinea;
    }

    public void setAnchoLinea(float anchoLinea) {
        this.anchoLinea = anchoLinea;
    }

    public void setColorContorno(Color colorContorno) {
        this.colorContorno = colorContorno;
    }

    public Color getColorPrimario() {
        return colorPrimario;
    }

    public void setColorPrimario(Color colorPrimario) {
        this.colorPrimario = colorPrimario;
    }

    public Color getColorSecundario() {
        return colorSecundario;
    }

    public void setColorSecundario(Color colorSecundario) {
        this.colorSecundario = colorSecundario;
    }

    public int getArch() {
        return arch;
    }

    public void setArch(int arch) {
        this.arch = arch;
    }

    public int getArcw() {
        return arcw;
    }

    public void setArcw(int arcw) {
        this.arcw = arcw;
    }

    public ModeloFicha getModeloFicha() {
        return modeloFicha;
    }

    public void setModeloFicha(ModeloFicha modeloFicha) {
        this.modeloFicha = modeloFicha;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
