/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package mx.com.exploradorhorarios;

import java.util.List;
import java.util.logging.Logger;
import mx.com.exploradorhorarios.visual.HorariosChildFactory;
import mx.com.exploradorhorarios.visual.HorariosRootNode;
import mx.com.servicios.explorador.DommyClass;
import mx.com.servicios.explorador.ExploradorSrv;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
//import org.openide.util.ImageUtilities;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.explorer.ExplorerManager;
import org.openide.nodes.Children;
import org.openide.util.Lookup;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
    dtd="-//mx.com.exploradorhorarios//ExploradorHorarios//EN",
    autostore=false
)
public final class ExploradorHorariosTopComponent extends TopComponent implements ExplorerManager.Provider{
    private static ExploradorHorariosTopComponent instance;
    private ExploradorSrv exploradorSrv;
    private ExplorerManager explorerManager = new ExplorerManager();
    /** path to the icon used by the component and its open action */
//    static final String ICON_PATH = "SET/PATH/TO/ICON/HERE";

    private static final String PREFERRED_ID = "ExploradorHorariosTopComponent";

    public ExploradorHorariosTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(ExploradorHorariosTopComponent.class, "CTL_ExploradorHorariosTopComponent"));
        setToolTipText(NbBundle.getMessage(ExploradorHorariosTopComponent.class, "HINT_ExploradorHorariosTopComponent"));
//        setIcon(ImageUtilities.loadImage(ICON_PATH, true));
	putClientProperty(TopComponent.PROP_CLOSING_DISABLED, Boolean.TRUE);
	putClientProperty(TopComponent.PROP_DRAGGING_DISABLED, Boolean.TRUE);
	putClientProperty(TopComponent.PROP_MAXIMIZATION_DISABLED, Boolean.TRUE);
	putClientProperty(TopComponent.PROP_SLIDING_DISABLED, Boolean.TRUE);
	putClientProperty(TopComponent.PROP_UNDOCKING_DISABLED, Boolean.TRUE);
	putClientProperty(TopComponent.PROP_KEEP_PREFERRED_SIZE_WHEN_SLIDED_IN, Boolean.TRUE);

        exploradorSrv = Lookup.getDefault().lookup(ExploradorSrv.class);
        List<DommyClass> lstResult = exploradorSrv.getListaHorarios();

        explorerManager.setRootContext(new HorariosRootNode(Children.create(new HorariosChildFactory(lstResult), true)));

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        beanTreeView1 = new org.openide.explorer.view.BeanTreeView();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(beanTreeView1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(beanTreeView1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openide.explorer.view.BeanTreeView beanTreeView1;
    // End of variables declaration//GEN-END:variables
    /**
     * Gets default instance. Do not use directly: reserved for *.settings files only,
     * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
     * To obtain the singleton instance, use {@link #findInstance}.
     */
    public static synchronized ExploradorHorariosTopComponent getDefault() {
        if (instance == null) {
            instance = new ExploradorHorariosTopComponent();
        }
        return instance;
    }

    /**
     * Obtain the ExploradorHorariosTopComponent instance. Never call {@link #getDefault} directly!
     */
    public static synchronized ExploradorHorariosTopComponent findInstance() {
        TopComponent win = WindowManager.getDefault().findTopComponent(PREFERRED_ID);
        if (win == null) {
            Logger.getLogger(ExploradorHorariosTopComponent.class.getName()).warning(
                    "Cannot find " + PREFERRED_ID + " component. It will not be located properly in the window system.");
            return getDefault();
        }
        if (win instanceof ExploradorHorariosTopComponent) {
            return (ExploradorHorariosTopComponent) win;
        }
        Logger.getLogger(ExploradorHorariosTopComponent.class.getName()).warning(
                "There seem to be multiple components with the '" + PREFERRED_ID +
                "' ID. That is a potential source of errors and unexpected behavior.");
        return getDefault();
    }

    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_ALWAYS;
    }

    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    Object readProperties(java.util.Properties p) {
        ExploradorHorariosTopComponent singleton = ExploradorHorariosTopComponent.getDefault();
        singleton.readPropertiesImpl(p);
        return singleton;
    }

    private void readPropertiesImpl(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }

    public ExplorerManager getExplorerManager() {
        return this.explorerManager;
    }
}
