/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OtroFrame.java
 *
 * Created on 21-abr-2009, 22:36:42
 */
package caafe.autorizacion;

import autorizacion.servicio.ServicioAutorizacion;
import caafe.table.celleditor.ButtonCellEditor;
import caafe.table.tablemodel.DetalleAutorizacion;
import caafes.def.Autorizaciones;
import caafes.def.Facturas;
import factura.servicio.ServicioFactura;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import otro.MiJDialog;
import otro.Pass;

/**
 *
 * @author Edgar
 */
public class Autoriza extends MiJDialog {

    public boolean bEstado;
    private int iEstatus = 0;
    public final static int NUEVO = 100;
    public final static int CONSULTAR = 101;
    public final static int EDITAR = 102;
    public Facturas facturaVo;
    public Autorizaciones autorizaVO;
    private Pass frmPass;
    private ButtonCellEditor buttonCellEditor;
//    private ButtonCellEditor buttonCellEditor;

    /** Creates new form OtroFrame */
    public Autoriza(ButtonCellEditor buttonCellEditor) {
        initComponents();
        this.buttonCellEditor = buttonCellEditor;
//        this.buttonCellEditor = buttonCellEditor;
    }

    public void actualizaForm(int iEstatus, BigDecimal idAutorizacion) {
        this.iEstatus = iEstatus;

        if (iEstatus == CONSULTAR) {

            jtxAutorizo.setEnabled(false);
            jcCaduca.setEnabled(false);
            jtxFolioFin.setEnabled(false);
            jtxFolioIncia.setEnabled(false);
            jtxNumAutoriza.setEnabled(false);
            jtxSolocitante.setEnabled(false);
            jcCreada.setEnabled(false);


            ServicioAutorizacion srvAutorizacion = new ServicioAutorizacion();
            ServicioFactura srvFactura = new ServicioFactura();
            Facturas facturaVO = srvFactura.obtieneFacturaFolioAutorizacion(idAutorizacion);

//            autorizaVO = srvAutorizacion.obtieneAutorizacion(idAutorizacion);
//
//            jtxNumAutoriza.setText(String.valueOf(autorizaVO.getIdAutorizacion()));
            jtxFolioIncia.setText(String.valueOf(autorizaVO.getFolioInicio()));
            jtxFolioFin.setText(String.valueOf(autorizaVO.getFolioFinal()));
            jtxAutorizo.setText(autorizaVO.getAutorizo());
            jtxSolocitante.setText(autorizaVO.getSolicitante());
            jcCaduca.setDate(autorizaVO.getCaducidad());

            jbAceptar.setText("Modificar");

            iEstatus = CONSULTAR;
        }
        if (iEstatus == NUEVO) {
            jtxAutorizo.setEnabled(true);
            jcCaduca.setEnabled(true);
            jtxFolioFin.setEnabled(true);
            jtxFolioIncia.setEnabled(true);
            jtxNumAutoriza.setEnabled(true);
            jtxSolocitante.setEnabled(true);
            jcCreada.setEnabled(true);
            jcCreada.setEnabled(true);

            limpiaForma();

            Calendar fechaActual = Calendar.getInstance();
            fechaActual.getInstance().getTime();
            jcCreada.setCalendar(fechaActual);
            fechaActual.add(Calendar.YEAR, 2);
            fechaActual.add(Calendar.DAY_OF_WEEK, 1);
            jcCaduca.setCalendar(fechaActual);
            jbAceptar.setText("Agregar");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbAceptar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jtxNumAutoriza = new javax.swing.JTextField();
        jtxSolocitante = new javax.swing.JTextField();
        jtxAutorizo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jcCaduca = new com.toedter.calendar.JDateChooser("dd/MM/yyyy", "##/##/####", '_');
        jLabel10 = new javax.swing.JLabel();
        jcCreada = new com.toedter.calendar.JDateChooser("dd/MM/yyyy", "##/##/####", '_');
        jtxFolioIncia = new javax.swing.JTextField();
        jtxFolioFin = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Autorización");
        setAlwaysOnTop(true);

        jLabel1.setText("Num Autorizacion");

        jLabel3.setText("Folios");

        jLabel4.setText("Solicitante");

        jLabel5.setText("Autorizo");

        jbAceptar.setText("Agregar");
        jbAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAceptarActionPerformed(evt);
            }
        });

        jbCancelar.setText("Salir");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jtxNumAutoriza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxNumAutorizaActionPerformed(evt);
            }
        });
        jtxNumAutoriza.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxNumAutorizaFocusLost(evt);
            }
        });
        jtxNumAutoriza.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxNumAutorizaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxNumAutorizaKeyReleased(evt);
            }
        });

        jtxSolocitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxSolocitanteActionPerformed(evt);
            }
        });
        jtxSolocitante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxSolocitanteKeyPressed(evt);
            }
        });

        jtxAutorizo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxAutorizoActionPerformed(evt);
            }
        });
        jtxAutorizo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxAutorizoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxAutorizoKeyReleased(evt);
            }
        });

        jLabel8.setText(" a");

        jLabel9.setText("Caduca dd/mm/AA");

        jcCaduca.setDateFormatString("dd/MM/yyyy");

        jLabel10.setText("Creada dd/mm/AA");

        jcCreada.setDateFormatString("dd/MM/yyyy");

        jtxFolioIncia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxFolioInciaActionPerformed(evt);
            }
        });
        jtxFolioIncia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxFolioInciaFocusLost(evt);
            }
        });
        jtxFolioIncia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxFolioInciaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxFolioInciaKeyReleased(evt);
            }
        });

        jtxFolioFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxFolioFinActionPerformed(evt);
            }
        });
        jtxFolioFin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxFolioFinFocusLost(evt);
            }
        });
        jtxFolioFin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxFolioFinKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxFolioFinKeyReleased(evt);
            }
        });

        jMenu1.setText("Archivo");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Agregar");
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Acerca");

        jMenuItem2.setText("Ayuda");
        jMenu2.add(jMenuItem2);

        jMenuItem4.setText("Acerca...");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(jLabel9))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxSolocitante, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(jtxAutorizo, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(jcCreada, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(jcCaduca, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtxFolioIncia)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8))
                                    .addComponent(jtxNumAutoriza, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jtxFolioFin, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxNumAutoriza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxFolioIncia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxFolioFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxSolocitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxAutorizo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcCreada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jcCaduca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregaAutorizacion() {
        ServicioAutorizacion srvAutoriza = new ServicioAutorizacion();
        ServicioFactura srvFactura = new ServicioFactura();
        String strAutoriza;
        List<Autorizaciones> lista;

        if (bEstado == true) {
            strAutoriza = jtxNumAutoriza.getText();
            lista = srvAutoriza.obtieneListaAutorizacionFolio(new BigDecimal(strAutoriza));
            if (lista != null) {
                if (lista.isEmpty()) {
                    creaAutoriza();
                } else {
                    JOptionPane.showMessageDialog(this, "El Numero de Autorizacion ya exciste", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                creaAutoriza();
            }
        }
    }

    private void creaAutoriza() {
        DetalleAutorizacion autoriza = null;

        if (bEstado == true) {
            autoriza = new DetalleAutorizacion();

            autoriza.setAutorizo(jtxAutorizo.getText());
            autoriza.setFolioInicio(new BigInteger(jtxFolioIncia.getText()));
            autoriza.setFolioFinal(new BigInteger(jtxFolioFin.getText()));
            autoriza.setCaducidad(jcCaduca.getDate());
            autoriza.setFechaCreacion(jcCreada.getDate());
            autoriza.setIdAutorizacion(new BigDecimal(jtxNumAutoriza.getText()));
            autoriza.setSolicitante(jtxSolocitante.getText());

            JOptionPane.showMessageDialog(this, "Datos agregados Correctamente", "OK", JOptionPane.INFORMATION_MESSAGE);
            this.buttonCellEditor.colocaAutorizacioVO(autoriza);
            this.dispose();
        }
    }

    private void modificaAutoriza() {
        ServicioAutorizacion srvAutoriza = new ServicioAutorizacion();
        Autorizaciones autoriza = null;

        srvAutoriza = new ServicioAutorizacion();

        autoriza = srvAutoriza.obtieneAutorizacion(new BigDecimal(jtxNumAutoriza.getText()));

        autoriza.setAutorizo(jtxAutorizo.getText());
        autoriza.setFolioInicio(new BigInteger(jtxFolioIncia.getText()));
        autoriza.setFolioFinal(new BigInteger(jtxFolioFin.getText()));
        autoriza.setCaducidad(jcCaduca.getDate());
        autoriza.setFechaCreacion(Calendar.getInstance().getTime());
//            autoriza.setIdAutorizacion(Long.valueOf(jtxNumAutoriza.getText()));
        autoriza.setSolicitante(jtxSolocitante.getText());
        autoriza.setExportado('N');
        srvAutoriza.modificaAutorizacion(autoriza);
    }

    private void jbAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAceptarActionPerformed
        switch (iEstatus) {
            case NUEVO:
                desborde();
                estado();
                folios();
                if (bEstado != false) {
                    agregaAutorizacion();
                }
                break;

            case CONSULTAR:
                if (frmPass == null) {
                    frmPass = new Pass(this, 1);
                }
                frmPass.limpiaFrame();
                frmPass.setVisible(true);
                frmPass.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                frmPass.setAlwaysOnTop(true);
                frmPass.setLocationRelativeTo(this);
                break;
            case EDITAR:
                modificaAutoriza();
                JOptionPane.showMessageDialog(this, "Datos Editados con éxito", "", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                break;
        }


}//GEN-LAST:event_jbAceptarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        this.dispose();
}//GEN-LAST:event_jbCancelarActionPerformed

    private void jtxSolocitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxSolocitanteActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jtxSolocitanteActionPerformed

    private void jtxAutorizoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxAutorizoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jtxAutorizoActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        this.dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jtxNumAutorizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxNumAutorizaActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jtxNumAutorizaActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jtxNumAutorizaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxNumAutorizaFocusLost
        BigDecimal bdNumeroAutorizacion;
        if (!jtxNumAutoriza.getText().equals("")) {
            try {
                bdNumeroAutorizacion = new BigDecimal(jtxNumAutoriza.getText());
            } catch (Exception exception) {
                jtxNumAutoriza.setText("");
                JOptionPane.showMessageDialog(this, "El Numero de Autorizaicon debe de ser numerico", "Error", JOptionPane.ERROR_MESSAGE);

            }
        }       // TODO add your handling code here:
    }//GEN-LAST:event_jtxNumAutorizaFocusLost

    private void jtxFolioInciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxFolioInciaActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jtxFolioInciaActionPerformed

    private void jtxFolioInciaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxFolioInciaFocusLost
        // TODO add your handling code here:
}//GEN-LAST:event_jtxFolioInciaFocusLost

    private void jtxFolioFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxFolioFinActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jtxFolioFinActionPerformed

    private void jtxFolioFinFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxFolioFinFocusLost
        // TODO add your handling code here:
}//GEN-LAST:event_jtxFolioFinFocusLost

    private void jtxFolioInciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxFolioInciaKeyPressed
        String cSubstring = jtxFolioIncia.getText();
        if (jtxFolioIncia.getText().length() >= 5 && ignoraKey(evt)) {
            JOptionPane.showMessageDialog(this, "El campo Folio inicial solo acepta 5 caracteres\n", "Demasiados caracteres", JOptionPane.ERROR_MESSAGE);
            jtxFolioIncia.setText(cSubstring.substring(0, 5));
        }
    }//GEN-LAST:event_jtxFolioInciaKeyPressed

    private void jtxFolioFinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxFolioFinKeyPressed
        String cSubstring = jtxFolioFin.getText();
        if (jtxFolioFin.getText().length() >= 5 && ignoraKey(evt)) {
            JOptionPane.showMessageDialog(this, "El campo Folio Final solo acepta 5 caracteres\n", "Demasiados caracteres", JOptionPane.ERROR_MESSAGE);
            jtxFolioFin.setText(cSubstring.substring(0, 5));
        }
    }//GEN-LAST:event_jtxFolioFinKeyPressed

    private void jtxNumAutorizaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxNumAutorizaKeyPressed
        String cSubstring = jtxNumAutoriza.getText();
        if (jtxNumAutoriza.getText().length() >= 20 && ignoraKey(evt)) {
            JOptionPane.showMessageDialog(this, "El campo Numero de Autorización solo acepta 20 caracteres\n", "Demasiados caracteres", JOptionPane.ERROR_MESSAGE);
            jtxNumAutoriza.setText(cSubstring.substring(0, 20));
        }
    }//GEN-LAST:event_jtxNumAutorizaKeyPressed

    private void jtxSolocitanteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxSolocitanteKeyPressed
        String cSubstring = jtxSolocitante.getText();
        if (jtxSolocitante.getText().length() >= 20 && ignoraKey(evt)) {
            JOptionPane.showMessageDialog(this, "El campo Solicitante solo acepta 20 caracteres\n", "Demasiados caracteres", JOptionPane.ERROR_MESSAGE);
            jtxSolocitante.setText(cSubstring.substring(0, 20));
        }
    }//GEN-LAST:event_jtxSolocitanteKeyPressed

    private void jtxAutorizoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxAutorizoKeyPressed
        String cSubstring = jtxAutorizo.getText();
        if (jtxAutorizo.getText().length() >= 20 && ignoraKey(evt)) {
            JOptionPane.showMessageDialog(this, "El campo Autorizo solo acepta 20 caracteres\n", "Demasiados caracteres", JOptionPane.ERROR_MESSAGE);
            jtxAutorizo.setText(cSubstring.substring(0, 20));
        }
    }//GEN-LAST:event_jtxAutorizoKeyPressed

    private void jtxNumAutorizaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxNumAutorizaKeyReleased
        BigDecimal bdCantidad = null;
        if (!jtxNumAutoriza.getText().equals("")) {
            try {
                bdCantidad = new BigDecimal(jtxNumAutoriza.getText());

            } catch (Exception exception) {
                JOptionPane.showMessageDialog(this, "El Numero de Autorizacion debe de ser numerico", "Error", JOptionPane.ERROR_MESSAGE);
                jtxNumAutoriza.setText("");
            }
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jtxNumAutorizaKeyReleased

    private void jtxFolioInciaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxFolioInciaKeyReleased
        BigDecimal bdCantidad = null;
        if (!jtxFolioIncia.getText().equals("")) {
            try {
                bdCantidad = new BigDecimal(jtxFolioIncia.getText());

            } catch (Exception exception) {
                JOptionPane.showMessageDialog(this, "El Folio inicial debe de ser numerico", "Error", JOptionPane.ERROR_MESSAGE);
                jtxFolioIncia.setText("");
            }
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jtxFolioInciaKeyReleased

    private void jtxFolioFinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxFolioFinKeyReleased
        BigDecimal bdCantidad = null;
        if (!jtxFolioFin.getText().equals("")) {
            try {
                bdCantidad = new BigDecimal(jtxFolioFin.getText());

            } catch (Exception exception) {
                JOptionPane.showMessageDialog(this, "El Folio final debe de ser numerico", "Error", JOptionPane.ERROR_MESSAGE);
                jtxFolioFin.setText("");
            }
        }             // TODO add your handling code here:
    }//GEN-LAST:event_jtxFolioFinKeyReleased

    private void jtxAutorizoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxAutorizoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxAutorizoKeyReleased

    public boolean ignoraKey(java.awt.event.KeyEvent evt) {
        if (evt.getKeyCode() == 10 || evt.getKeyCode() == 18 || evt.getKeyCode() == 17 || evt.getKeyCode() == 8 || evt.getKeyCode() == 127 || evt.getKeyCode() == 155 || evt.getKeyCode() == 16 || evt.getKeyCode() == 20 || evt.getKeyCode() == 33 || evt.getKeyCode() == 34 || evt.getKeyCode() == 35 || evt.getKeyCode() == 36 || evt.getKeyCode() == 37 || evt.getKeyCode() == 38 || evt.getKeyCode() == 39 || evt.getKeyCode() == 40) {
            return false;
        } else {
            return true;
        }
    }

    public void estado() {
        String sNumAutoriza;
        String sFolioInicia;
        String sFolioFin;
        String sSolicitante;
        String sAutorizo;
        Date clCaduca = jcCaduca.getDate();


        StringBuilder sbFaltantes = new StringBuilder("");
        boolean bFaltan = false;

        sNumAutoriza = jtxNumAutoriza.getText();
        sFolioInicia = jtxFolioIncia.getText();
        sFolioFin = jtxFolioFin.getText();
        sSolicitante = jtxSolocitante.getText();
        sAutorizo = jtxAutorizo.getText();

        if (sNumAutoriza.equals("")) {
            sbFaltantes.append("Numero de Autorizacion \n");
            bFaltan = true;
        }
        if (sFolioInicia.equals("")) {
            sbFaltantes.append("Inicio de Folios\n");
            bFaltan = true;
        }
        if (sFolioFin.equals("")) {
            sbFaltantes.append("Fin de Folios\n");
            bFaltan = true;
        }
        if (sSolicitante.equals("")) {
            sbFaltantes.append("Solicitante\n");
            bFaltan = true;
        }
        if (sAutorizo.equals("")) {
            sbFaltantes.append("Autorizo\n");
            bFaltan = true;
        }
        if (clCaduca == null) {
            sbFaltantes.append("Fecha Caducidad\n");
            bFaltan = true;
        }
        if (bFaltan == true) {
            JOptionPane.showMessageDialog(this, "Los campos:\n" + sbFaltantes + "Son requeridos", "Campos faltantes", JOptionPane.ERROR_MESSAGE);
            bEstado = false;
        } else {

            bEstado = true;
        }
        bFaltan = false;
    }

    public void desborde() {
        StringBuilder sbError = new StringBuilder("");
        boolean bEntra = false;



        if (jtxNumAutoriza.getText().length() > 20) {
            sbError.append("El campo Numero de Autorizacion solo acepta 20 caracteres\n");
            bEntra = true;
        }
        if (jtxSolocitante.getText().length() > 20) {
            sbError.append("El campo Solicitante solo acepta 20 caracteres\n");
            bEntra = true;

        }
        if (jtxAutorizo.getText().length() > 20) {
            sbError.append("El campo Autorizo solo acepta 20 caracteres \n");
            bEntra = true;
        }


        if (bEntra == true) {

            JOptionPane.showMessageDialog(this, "" + sbError, "Demasiados caracteres", JOptionPane.ERROR_MESSAGE);
            bEstado = false;
        } else {
            bEstado = true;
        }

    }

    private void folios() {
        Long folioInicia = Long.valueOf(jtxFolioIncia.getText());
        Long folioFin = Long.valueOf(jtxFolioFin.getText());

        if (folioInicia >= folioFin) {
            JOptionPane.showMessageDialog(this, "EL Folio Final debe ser mas Grande que el de Inicio", "Error", JOptionPane.ERROR_MESSAGE);
            bEstado = false;
        }
    }

    private void limpiaForma() {
        jtxAutorizo.setText("");
        jtxFolioFin.setText("");
        jtxFolioIncia.setText("");
        jtxNumAutoriza.setText("");
        jtxSolocitante.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JButton jbAceptar;
    private javax.swing.JButton jbCancelar;
    private com.toedter.calendar.JDateChooser jcCaduca;
    private com.toedter.calendar.JDateChooser jcCreada;
    private javax.swing.JTextField jtxAutorizo;
    private javax.swing.JTextField jtxFolioFin;
    private javax.swing.JTextField jtxFolioIncia;
    private javax.swing.JTextField jtxNumAutoriza;
    private javax.swing.JTextField jtxSolocitante;
    // End of variables declaration//GEN-END:variables

    @Override
    public void cbPasswprd() {
        jtxAutorizo.setEnabled(true);
        jtxFolioFin.setEnabled(true);
        jtxFolioIncia.setEnabled(true);
        jtxSolocitante.setEnabled(true);
        jcCaduca.setEnabled(true);
        iEstatus = EDITAR;
        jbAceptar.setText("Guardar");
    }
}
